// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doravota/sponsor/v1/sponsor.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ContractSponsor defines the sponsor information for a contract
type ContractSponsor struct {
	ContractAddress string        `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	IsSponsored     bool          `protobuf:"varint,2,opt,name=is_sponsored,json=isSponsored,proto3" json:"is_sponsored,omitempty"`
	SponsorAddress  string        `protobuf:"bytes,3,opt,name=sponsor_address,json=sponsorAddress,proto3" json:"sponsor_address,omitempty"`
	CreatedAt       int64         `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64         `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MaxGrantPerUser []*types.Coin `protobuf:"bytes,6,rep,name=max_grant_per_user,json=maxGrantPerUser,proto3" json:"max_grant_per_user,omitempty"`
}

func (m *ContractSponsor) Reset()         { *m = ContractSponsor{} }
func (m *ContractSponsor) String() string { return proto.CompactTextString(m) }
func (*ContractSponsor) ProtoMessage()    {}
func (*ContractSponsor) Descriptor() ([]byte, []int) {
	return fileDescriptor_eab4c65bac3c53c6, []int{0}
}
func (m *ContractSponsor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractSponsor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractSponsor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractSponsor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractSponsor.Merge(m, src)
}
func (m *ContractSponsor) XXX_Size() int {
	return m.Size()
}
func (m *ContractSponsor) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractSponsor.DiscardUnknown(m)
}

var xxx_messageInfo_ContractSponsor proto.InternalMessageInfo

func (m *ContractSponsor) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ContractSponsor) GetIsSponsored() bool {
	if m != nil {
		return m.IsSponsored
	}
	return false
}

func (m *ContractSponsor) GetSponsorAddress() string {
	if m != nil {
		return m.SponsorAddress
	}
	return ""
}

func (m *ContractSponsor) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ContractSponsor) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ContractSponsor) GetMaxGrantPerUser() []*types.Coin {
	if m != nil {
		return m.MaxGrantPerUser
	}
	return nil
}

// GenesisState defines the sponsor module's genesis state
type GenesisState struct {
	Sponsors []*ContractSponsor `protobuf:"bytes,1,rep,name=sponsors,proto3" json:"sponsors,omitempty"`
	Params   *Params            `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_eab4c65bac3c53c6, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetSponsors() []*ContractSponsor {
	if m != nil {
		return m.Sponsors
	}
	return nil
}

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

// UserGrantUsage tracks how much grant a user has used for a specific contract
type UserGrantUsage struct {
	UserAddress     string        `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	ContractAddress string        `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TotalGrantUsed  []*types.Coin `protobuf:"bytes,3,rep,name=total_grant_used,json=totalGrantUsed,proto3" json:"total_grant_used,omitempty"`
	LastUsedTime    int64         `protobuf:"varint,4,opt,name=last_used_time,json=lastUsedTime,proto3" json:"last_used_time,omitempty"`
}

func (m *UserGrantUsage) Reset()         { *m = UserGrantUsage{} }
func (m *UserGrantUsage) String() string { return proto.CompactTextString(m) }
func (*UserGrantUsage) ProtoMessage()    {}
func (*UserGrantUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_eab4c65bac3c53c6, []int{2}
}
func (m *UserGrantUsage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserGrantUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserGrantUsage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserGrantUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGrantUsage.Merge(m, src)
}
func (m *UserGrantUsage) XXX_Size() int {
	return m.Size()
}
func (m *UserGrantUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGrantUsage.DiscardUnknown(m)
}

var xxx_messageInfo_UserGrantUsage proto.InternalMessageInfo

func (m *UserGrantUsage) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *UserGrantUsage) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *UserGrantUsage) GetTotalGrantUsed() []*types.Coin {
	if m != nil {
		return m.TotalGrantUsed
	}
	return nil
}

func (m *UserGrantUsage) GetLastUsedTime() int64 {
	if m != nil {
		return m.LastUsedTime
	}
	return 0
}

// Params defines the parameters for the sponsor module
type Params struct {
	// Maximum number of sponsors per contract
	MaxSponsorsPerContract uint64 `protobuf:"varint,1,opt,name=max_sponsors_per_contract,json=maxSponsorsPerContract,proto3" json:"max_sponsors_per_contract,omitempty"`
	// Whether sponsorship is globally enabled
	SponsorshipEnabled bool `protobuf:"varint,2,opt,name=sponsorship_enabled,json=sponsorshipEnabled,proto3" json:"sponsorship_enabled,omitempty"`
	// Maximum gas limit per sponsored transaction
	MaxGasPerSponsorship uint64 `protobuf:"varint,3,opt,name=max_gas_per_sponsorship,json=maxGasPerSponsorship,proto3" json:"max_gas_per_sponsorship,omitempty"`
	// Minimum contract age in seconds before it can be sponsored
	MinContractAge uint64 `protobuf:"varint,4,opt,name=min_contract_age,json=minContractAge,proto3" json:"min_contract_age,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_eab4c65bac3c53c6, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxSponsorsPerContract() uint64 {
	if m != nil {
		return m.MaxSponsorsPerContract
	}
	return 0
}

func (m *Params) GetSponsorshipEnabled() bool {
	if m != nil {
		return m.SponsorshipEnabled
	}
	return false
}

func (m *Params) GetMaxGasPerSponsorship() uint64 {
	if m != nil {
		return m.MaxGasPerSponsorship
	}
	return 0
}

func (m *Params) GetMinContractAge() uint64 {
	if m != nil {
		return m.MinContractAge
	}
	return 0
}

func init() {
	proto.RegisterType((*ContractSponsor)(nil), "doravota.sponsor.v1.ContractSponsor")
	proto.RegisterType((*GenesisState)(nil), "doravota.sponsor.v1.GenesisState")
	proto.RegisterType((*UserGrantUsage)(nil), "doravota.sponsor.v1.UserGrantUsage")
	proto.RegisterType((*Params)(nil), "doravota.sponsor.v1.Params")
}

func init() { proto.RegisterFile("doravota/sponsor/v1/sponsor.proto", fileDescriptor_eab4c65bac3c53c6) }

var fileDescriptor_eab4c65bac3c53c6 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0x23, 0xdb, 0x35, 0xc9, 0xda, 0xd8, 0x66, 0x53, 0x5a, 0xa7, 0xa5, 0xc2, 0x31, 0x81,
	0xba, 0x87, 0x48, 0x38, 0xa1, 0x87, 0xd2, 0x4b, 0x5d, 0xb7, 0xc9, 0xd5, 0xc8, 0xf5, 0xa5, 0x17,
	0x31, 0x96, 0x06, 0x67, 0xc1, 0xd2, 0x8a, 0xdd, 0xb5, 0x51, 0x1e, 0xa0, 0xd7, 0xd2, 0xc7, 0x6a,
	0x6f, 0xb9, 0x14, 0x7a, 0x2c, 0xf6, 0x8b, 0x94, 0x95, 0x76, 0x9d, 0x10, 0x0c, 0xbd, 0x89, 0x6f,
	0xe6, 0x9b, 0x3f, 0xbf, 0xd1, 0x92, 0xd3, 0x98, 0x0b, 0x58, 0x73, 0x05, 0xbe, 0xcc, 0x78, 0x2a,
	0xb9, 0xf0, 0xd7, 0x43, 0xfb, 0xe9, 0x65, 0x82, 0x2b, 0x4e, 0x8f, 0x6d, 0x8a, 0x67, 0xf5, 0xf5,
	0xf0, 0x85, 0x1b, 0x71, 0x99, 0x70, 0xe9, 0xcf, 0x41, 0xa2, 0xbf, 0x1e, 0xce, 0x51, 0xc1, 0xd0,
	0x8f, 0x38, 0x4b, 0x4b, 0x53, 0xff, 0x7b, 0x85, 0xb4, 0xc7, 0x3c, 0x55, 0x02, 0x22, 0x35, 0x2d,
	0x6d, 0xf4, 0x0d, 0xe9, 0x44, 0x46, 0x0a, 0x21, 0x8e, 0x05, 0x4a, 0xd9, 0x75, 0x7a, 0xce, 0xe0,
	0x28, 0x68, 0x5b, 0x7d, 0x54, 0xca, 0xf4, 0x94, 0x34, 0x99, 0x0c, 0x4d, 0x3f, 0x8c, 0xbb, 0x95,
	0x9e, 0x33, 0x38, 0x0c, 0x1a, 0x4c, 0x4e, 0xad, 0x44, 0x5f, 0x93, 0xb6, 0x89, 0xef, 0x8a, 0x55,
	0x8b, 0x62, 0x2d, 0x23, 0xdb, 0x5a, 0xaf, 0x08, 0x89, 0x04, 0x82, 0xc2, 0x38, 0x04, 0xd5, 0xad,
	0xf5, 0x9c, 0x41, 0x35, 0x38, 0x32, 0xca, 0x48, 0xe9, 0xf0, 0x2a, 0x8b, 0x6d, 0xf8, 0x49, 0x19,
	0x36, 0xca, 0x48, 0xd1, 0x2b, 0x42, 0x13, 0xc8, 0xc3, 0x85, 0x80, 0x54, 0x85, 0x19, 0x8a, 0x70,
	0x25, 0x51, 0x74, 0xeb, 0xbd, 0xea, 0xa0, 0x71, 0x71, 0xe2, 0x95, 0x14, 0x3c, 0x4d, 0xc1, 0x33,
	0x14, 0xbc, 0x31, 0x67, 0x69, 0xd0, 0x4e, 0x20, 0xbf, 0xd6, 0x9e, 0x09, 0x8a, 0x99, 0x44, 0xd1,
	0xff, 0xe6, 0x90, 0xe6, 0x35, 0xa6, 0x28, 0x99, 0x9c, 0x2a, 0x50, 0x48, 0x3f, 0x90, 0x43, 0x33,
	0xa8, 0xa6, 0xa0, 0xcb, 0x9d, 0x79, 0x7b, 0x48, 0x7b, 0x8f, 0x28, 0x06, 0x3b, 0x17, 0xbd, 0x24,
	0xf5, 0x0c, 0x04, 0x24, 0xb2, 0xc0, 0xd3, 0xb8, 0x78, 0xb9, 0xd7, 0x3f, 0x29, 0x52, 0x02, 0x93,
	0xda, 0xff, 0xe5, 0x90, 0x96, 0x1e, 0xa8, 0x18, 0x6e, 0x26, 0x61, 0x81, 0x1a, 0xb6, 0x5e, 0xea,
	0xd1, 0x4d, 0x1a, 0x5a, 0xb3, 0x0c, 0xf7, 0x9d, 0xae, 0xb2, 0xff, 0x74, 0x63, 0xd2, 0x51, 0x5c,
	0xc1, 0xd2, 0x20, 0x5b, 0x49, 0x8c, 0xbb, 0xd5, 0xff, 0xe1, 0x6a, 0x15, 0x16, 0x33, 0x13, 0xc6,
	0xf4, 0x8c, 0xb4, 0x96, 0x20, 0x4b, 0x77, 0xa8, 0x58, 0x82, 0xe6, 0x6e, 0x4d, 0xad, 0xea, 0x8c,
	0x2f, 0x2c, 0xc1, 0xfe, 0x6f, 0x87, 0xd4, 0xcb, 0xf5, 0xe8, 0x3b, 0x72, 0xa2, 0xcf, 0x64, 0xd9,
	0x14, 0x97, 0xb2, 0x93, 0x15, 0x0b, 0xd5, 0x82, 0x67, 0x09, 0xe4, 0x06, 0xa2, 0x9c, 0xa0, 0xb0,
	0x5c, 0xa9, 0x4f, 0x8e, 0xad, 0xed, 0x86, 0x65, 0x21, 0xa6, 0x30, 0x5f, 0xee, 0x7e, 0x39, 0xfa,
	0x20, 0xf4, 0xb9, 0x8c, 0xd0, 0xb7, 0xe4, 0x79, 0xf1, 0x4b, 0x40, 0xd9, 0xe6, 0x41, 0x46, 0xf1,
	0x07, 0xd6, 0x82, 0xa7, 0xfa, 0xf8, 0xa0, 0x9b, 0x4c, 0xef, 0x63, 0x74, 0x40, 0x3a, 0x09, 0x4b,
	0xc3, 0x7b, 0x8e, 0x8b, 0x72, 0xab, 0x5a, 0xd0, 0x4a, 0x58, 0x6a, 0xc7, 0x19, 0x2d, 0xf0, 0xe3,
	0xec, 0xe7, 0xc6, 0x75, 0xee, 0x36, 0xae, 0xf3, 0x77, 0xe3, 0x3a, 0x3f, 0xb6, 0xee, 0xc1, 0xdd,
	0xd6, 0x3d, 0xf8, 0xb3, 0x75, 0x0f, 0xbe, 0xbe, 0x5f, 0x30, 0x75, 0xb3, 0x9a, 0x7b, 0x11, 0x4f,
	0xfc, 0x4f, 0x5c, 0xc0, 0x15, 0x44, 0x8a, 0x8b, 0x5b, 0x7f, 0xf7, 0x8a, 0x73, 0xfb, 0x78, 0xcf,
	0x6d, 0x9f, 0x73, 0x95, 0xfb, 0xea, 0x36, 0x43, 0x39, 0xaf, 0x17, 0x4f, 0xf3, 0xf2, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0xb4, 0x80, 0xe6, 0xf4, 0x03, 0x00, 0x00,
}

func (m *ContractSponsor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractSponsor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractSponsor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxGrantPerUser) > 0 {
		for iNdEx := len(m.MaxGrantPerUser) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxGrantPerUser[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSponsor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintSponsor(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x28
	}
	if m.CreatedAt != 0 {
		i = encodeVarintSponsor(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SponsorAddress) > 0 {
		i -= len(m.SponsorAddress)
		copy(dAtA[i:], m.SponsorAddress)
		i = encodeVarintSponsor(dAtA, i, uint64(len(m.SponsorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.IsSponsored {
		i--
		if m.IsSponsored {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintSponsor(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSponsor(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sponsors) > 0 {
		for iNdEx := len(m.Sponsors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sponsors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSponsor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *UserGrantUsage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserGrantUsage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserGrantUsage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUsedTime != 0 {
		i = encodeVarintSponsor(dAtA, i, uint64(m.LastUsedTime))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TotalGrantUsed) > 0 {
		for iNdEx := len(m.TotalGrantUsed) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalGrantUsed[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSponsor(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintSponsor(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserAddress) > 0 {
		i -= len(m.UserAddress)
		copy(dAtA[i:], m.UserAddress)
		i = encodeVarintSponsor(dAtA, i, uint64(len(m.UserAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinContractAge != 0 {
		i = encodeVarintSponsor(dAtA, i, uint64(m.MinContractAge))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxGasPerSponsorship != 0 {
		i = encodeVarintSponsor(dAtA, i, uint64(m.MaxGasPerSponsorship))
		i--
		dAtA[i] = 0x18
	}
	if m.SponsorshipEnabled {
		i--
		if m.SponsorshipEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MaxSponsorsPerContract != 0 {
		i = encodeVarintSponsor(dAtA, i, uint64(m.MaxSponsorsPerContract))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSponsor(dAtA []byte, offset int, v uint64) int {
	offset -= sovSponsor(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ContractSponsor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovSponsor(uint64(l))
	}
	if m.IsSponsored {
		n += 2
	}
	l = len(m.SponsorAddress)
	if l > 0 {
		n += 1 + l + sovSponsor(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovSponsor(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovSponsor(uint64(m.UpdatedAt))
	}
	if len(m.MaxGrantPerUser) > 0 {
		for _, e := range m.MaxGrantPerUser {
			l = e.Size()
			n += 1 + l + sovSponsor(uint64(l))
		}
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sponsors) > 0 {
		for _, e := range m.Sponsors {
			l = e.Size()
			n += 1 + l + sovSponsor(uint64(l))
		}
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovSponsor(uint64(l))
	}
	return n
}

func (m *UserGrantUsage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserAddress)
	if l > 0 {
		n += 1 + l + sovSponsor(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovSponsor(uint64(l))
	}
	if len(m.TotalGrantUsed) > 0 {
		for _, e := range m.TotalGrantUsed {
			l = e.Size()
			n += 1 + l + sovSponsor(uint64(l))
		}
	}
	if m.LastUsedTime != 0 {
		n += 1 + sovSponsor(uint64(m.LastUsedTime))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxSponsorsPerContract != 0 {
		n += 1 + sovSponsor(uint64(m.MaxSponsorsPerContract))
	}
	if m.SponsorshipEnabled {
		n += 2
	}
	if m.MaxGasPerSponsorship != 0 {
		n += 1 + sovSponsor(uint64(m.MaxGasPerSponsorship))
	}
	if m.MinContractAge != 0 {
		n += 1 + sovSponsor(uint64(m.MinContractAge))
	}
	return n
}

func sovSponsor(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSponsor(x uint64) (n int) {
	return sovSponsor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContractSponsor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSponsor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractSponsor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractSponsor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSponsored", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSponsored = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SponsorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SponsorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGrantPerUser", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxGrantPerUser = append(m.MaxGrantPerUser, &types.Coin{})
			if err := m.MaxGrantPerUser[len(m.MaxGrantPerUser)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSponsor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSponsor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSponsor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sponsors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sponsors = append(m.Sponsors, &ContractSponsor{})
			if err := m.Sponsors[len(m.Sponsors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSponsor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSponsor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserGrantUsage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSponsor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserGrantUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserGrantUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalGrantUsed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSponsor
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSponsor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalGrantUsed = append(m.TotalGrantUsed, &types.Coin{})
			if err := m.TotalGrantUsed[len(m.TotalGrantUsed)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUsedTime", wireType)
			}
			m.LastUsedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUsedTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSponsor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSponsor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSponsor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSponsorsPerContract", wireType)
			}
			m.MaxSponsorsPerContract = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSponsorsPerContract |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SponsorshipEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SponsorshipEnabled = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasPerSponsorship", wireType)
			}
			m.MaxGasPerSponsorship = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGasPerSponsorship |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinContractAge", wireType)
			}
			m.MinContractAge = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinContractAge |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSponsor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSponsor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSponsor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSponsor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSponsor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSponsor
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSponsor
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSponsor
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSponsor        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSponsor          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSponsor = fmt.Errorf("proto: unexpected end of group")
)
