package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"sync"
	"time"
)

const maxRPCResponseBytes = 1 << 20

type broadcastRequest struct {
	JSONRPC string            `json:"jsonrpc"`
	ID      int               `json:"id"`
	Method  string            `json:"method"`
	Params  map[string]string `json:"params"`
}

type broadcastRPCResponse struct {
	JSONRPC string `json:"jsonrpc"`
	ID      int    `json:"id"`
	Result  struct {
		Code      uint32 `json:"code"`
		Data      string `json:"data"`
		Log       string `json:"log"`
		Codespace string `json:"codespace"`
		Hash      string `json:"hash"`
	} `json:"result"`
	Error *struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
		Data    string `json:"data"`
	} `json:"error,omitempty"`
}

type broadcastJob struct {
	line   int
	record txRecord
}

type broadcastResult struct {
	Line       int    `json:"line"`
	Mode       string `json:"mode"`
	Index      int    `json:"index"`
	Expected   string `json:"expected_hash"`
	RPCHash    string `json:"rpc_hash,omitempty"`
	Accepted   bool   `json:"accepted"`
	Code       uint32 `json:"code,omitempty"`
	Codespace  string `json:"codespace,omitempty"`
	Log        string `json:"log,omitempty"`
	HTTPStatus int    `json:"http_status,omitempty"`
	Error      string `json:"error,omitempty"`
	LatencyMS  int64  `json:"latency_ms"`
	LatencyUS  int64  `json:"latency_us"`
	Submitted  string `json:"submitted_at_utc"`
	Completed  string `json:"completed_at_utc"`
}

type broadcastSummary struct {
	Input        string                           `json:"input"`
	RPC          string                           `json:"rpc"`
	Concurrency  int                              `json:"concurrency"`
	Expected     string                           `json:"expected_outcome"`
	RatePerSec   float64                          `json:"rate_per_second"`
	Total        int                              `json:"total"`
	Accepted     int                              `json:"accepted"`
	Rejected     int                              `json:"rejected"`
	TransportErr int                              `json:"transport_errors"`
	ElapsedMS    int64                            `json:"elapsed_ms"`
	LatencyP50US int64                            `json:"latency_p50_us"`
	LatencyP95US int64                            `json:"latency_p95_us"`
	LatencyP99US int64                            `json:"latency_p99_us"`
	CodeCounts   map[string]int                   `json:"code_counts"`
	ModeOutcomes map[string]*broadcastModeOutcome `json:"mode_outcomes"`
}

type broadcastModeOutcome struct {
	Total        int            `json:"total"`
	Accepted     int            `json:"accepted"`
	Rejected     int            `json:"rejected"`
	TransportErr int            `json:"transport_errors"`
	CodeCounts   map[string]int `json:"code_counts"`
}

func broadcast(arguments []string) {
	flags := flag.NewFlagSet("broadcast", flag.ExitOnError)
	inputPath := flags.String("input", "", "transaction JSONL generated by pqcload")
	rpcURL := flags.String("rpc", "http://127.0.0.1:37657", "CometBFT RPC URL")
	outputPath := flags.String("out", "", "new JSONL result path")
	concurrency := flags.Int("concurrency", 32, "parallel RPC requests")
	timeout := flags.Duration("timeout", 30*time.Second, "per-request timeout")
	rate := flags.Float64("rate", 0, "maximum submission rate in transactions per second; zero is unlimited")
	expected := flags.String("expect", "accepted", "expected outcome: accepted, rejected, or any")
	if err := flags.Parse(arguments); err != nil {
		fatalf("parse broadcast flags: %v", err)
	}
	if *inputPath == "" || *outputPath == "" || *rpcURL == "" || *concurrency < 1 || *concurrency > 256 || *rate < 0 ||
		(*expected != "accepted" && *expected != "rejected" && *expected != "any") {
		fatalf("--input, --out, --rpc and concurrency in [1,256] are required")
	}
	input, err := os.Open(*inputPath)
	if err != nil {
		fatalf("open transaction input: %v", err)
	}
	defer input.Close()
	output, err := os.OpenFile(*outputPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		fatalf("create broadcast result: %v", err)
	}
	defer output.Close()

	client := &http.Client{Timeout: *timeout}
	jobs := make(chan broadcastJob, *concurrency*2)
	results := make(chan broadcastResult, *concurrency*2)
	var workers sync.WaitGroup
	for range *concurrency {
		workers.Add(1)
		go func() {
			defer workers.Done()
			for job := range jobs {
				results <- submitTransaction(client, *rpcURL, job)
			}
		}()
	}
	go func() {
		workers.Wait()
		close(results)
	}()

	started := time.Now()
	go func() {
		scanner := bufio.NewScanner(input)
		scanner.Buffer(make([]byte, 64*1024), 16*1024*1024)
		line := 0
		for scanner.Scan() {
			line++
			if *rate > 0 {
				target := started.Add(time.Duration(float64(time.Second) * float64(line-1) / *rate))
				if delay := time.Until(target); delay > 0 {
					time.Sleep(delay)
				}
			}
			var record txRecord
			if err := json.Unmarshal(scanner.Bytes(), &record); err != nil {
				results <- broadcastResult{Line: line, Error: fmt.Sprintf("decode input: %v", err)}
				continue
			}
			jobs <- broadcastJob{line: line, record: record}
		}
		if err := scanner.Err(); err != nil {
			results <- broadcastResult{Error: fmt.Sprintf("scan input: %v", err)}
		}
		close(jobs)
	}()

	buffer := bufio.NewWriterSize(output, 1024*1024)
	summary := broadcastSummary{
		Input: *inputPath, RPC: *rpcURL, Concurrency: *concurrency,
		Expected: *expected, RatePerSec: *rate, CodeCounts: make(map[string]int),
		ModeOutcomes: make(map[string]*broadcastModeOutcome),
	}
	latencies := make([]int64, 0, 1024)
	for result := range results {
		encoded, err := json.Marshal(result)
		if err != nil {
			fatalf("encode broadcast result: %v", err)
		}
		if _, err := buffer.Write(append(encoded, '\n')); err != nil {
			fatalf("write broadcast result: %v", err)
		}
		summary.Total++
		mode := result.Mode
		if mode == "" {
			mode = "unknown"
		}
		outcome := summary.ModeOutcomes[mode]
		if outcome == nil {
			outcome = &broadcastModeOutcome{CodeCounts: make(map[string]int)}
			summary.ModeOutcomes[mode] = outcome
		}
		outcome.Total++
		if result.Accepted {
			summary.Accepted++
			outcome.Accepted++
		} else {
			summary.Rejected++
			outcome.Rejected++
		}
		if result.Error != "" {
			summary.TransportErr++
			outcome.TransportErr++
		}
		if result.Error == "" {
			key := fmt.Sprintf("%s/%d", result.Codespace, result.Code)
			summary.CodeCounts[key]++
			outcome.CodeCounts[key]++
		}
		latencies = append(latencies, result.LatencyUS)
	}
	if err := buffer.Flush(); err != nil {
		fatalf("flush broadcast results: %v", err)
	}
	summary.ElapsedMS = time.Since(started).Milliseconds()
	sort.Slice(latencies, func(i, j int) bool { return latencies[i] < latencies[j] })
	summary.LatencyP50US = percentileInt64(latencies, 0.50)
	summary.LatencyP95US = percentileInt64(latencies, 0.95)
	summary.LatencyP99US = percentileInt64(latencies, 0.99)
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(summary); err != nil {
		fatalf("print broadcast summary: %v", err)
	}
	failedExpectation := summary.TransportErr != 0
	switch *expected {
	case "accepted":
		failedExpectation = failedExpectation || summary.Rejected != 0
	case "rejected":
		failedExpectation = failedExpectation || summary.Accepted != 0
	}
	if failedExpectation {
		os.Exit(2)
	}
}

func submitTransaction(client *http.Client, rpcURL string, job broadcastJob) (result broadcastResult) {
	result = broadcastResult{
		Line: job.line, Mode: job.record.Mode, Index: job.record.Index, Expected: job.record.Hash,
	}
	started := time.Now()
	result.Submitted = started.UTC().Format(time.RFC3339Nano)
	defer func() {
		result.Completed = time.Now().UTC().Format(time.RFC3339Nano)
		result.LatencyUS = time.Since(started).Microseconds()
		result.LatencyMS = result.LatencyUS / 1_000
	}()
	payload, err := json.Marshal(broadcastRequest{
		JSONRPC: "2.0", ID: job.line, Method: "broadcast_tx_sync",
		Params: map[string]string{"tx": job.record.TxBase64},
	})
	if err != nil {
		result.Error = fmt.Sprintf("encode request: %v", err)
		return result
	}
	response, err := client.Post(rpcURL, "application/json", bytes.NewReader(payload))
	if err != nil {
		result.Error = err.Error()
		return result
	}
	defer response.Body.Close()
	result.HTTPStatus = response.StatusCode
	body, err := io.ReadAll(io.LimitReader(response.Body, maxRPCResponseBytes+1))
	if err != nil {
		result.Error = fmt.Sprintf("read response: %v", err)
		return result
	}
	if len(body) > maxRPCResponseBytes {
		result.Error = "RPC response exceeds 1 MiB"
		return result
	}
	var decoded broadcastRPCResponse
	if err := json.Unmarshal(body, &decoded); err != nil {
		result.Error = fmt.Sprintf("decode RPC response: %v", err)
		return result
	}
	if decoded.Error != nil {
		result.Error = fmt.Sprintf("RPC %d: %s: %s", decoded.Error.Code, decoded.Error.Message, decoded.Error.Data)
		return result
	}
	result.RPCHash = decoded.Result.Hash
	result.Code = decoded.Result.Code
	result.Codespace = decoded.Result.Codespace
	result.Log = decoded.Result.Log
	result.Accepted = response.StatusCode >= 200 && response.StatusCode < 300 && decoded.Result.Code == 0
	return result
}

func percentileInt64(values []int64, quantile float64) int64 {
	if len(values) == 0 {
		return 0
	}
	index := int(quantile*float64(len(values)-1) + 0.5)
	if index < 0 {
		index = 0
	}
	if index >= len(values) {
		index = len(values) - 1
	}
	return values[index]
}
