// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doravota/pqcauth/v1/extension.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ExtensionPQCAuth is a critical TxBody extension. There must be at most one
// instance and entries must be in the same order as AuthInfo signer_infos.
type ExtensionPQCAuth struct {
	FormatVersion uint32               `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Signatures    []SignerPQCSignature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures"`
}

func (m *ExtensionPQCAuth) Reset()         { *m = ExtensionPQCAuth{} }
func (m *ExtensionPQCAuth) String() string { return proto.CompactTextString(m) }
func (*ExtensionPQCAuth) ProtoMessage()    {}
func (*ExtensionPQCAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c0e282b72d300f1, []int{0}
}
func (m *ExtensionPQCAuth) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExtensionPQCAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExtensionPQCAuth.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExtensionPQCAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtensionPQCAuth.Merge(m, src)
}
func (m *ExtensionPQCAuth) XXX_Size() int {
	return m.Size()
}
func (m *ExtensionPQCAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtensionPQCAuth.DiscardUnknown(m)
}

var xxx_messageInfo_ExtensionPQCAuth proto.InternalMessageInfo

func (m *ExtensionPQCAuth) GetFormatVersion() uint32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

func (m *ExtensionPQCAuth) GetSignatures() []SignerPQCSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

// SignerPQCSignature carries the detached PQC signature for one signer.
type SignerPQCSignature struct {
	Signer        string    `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	SignerIndex   uint32    `protobuf:"varint,2,opt,name=signer_index,json=signerIndex,proto3" json:"signer_index,omitempty"`
	KeyId         uint64    `protobuf:"varint,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     Algorithm `protobuf:"varint,4,opt,name=algorithm,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"algorithm,omitempty"`
	PolicyVersion uint64    `protobuf:"varint,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Signature     []byte    `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SignerPQCSignature) Reset()         { *m = SignerPQCSignature{} }
func (m *SignerPQCSignature) String() string { return proto.CompactTextString(m) }
func (*SignerPQCSignature) ProtoMessage()    {}
func (*SignerPQCSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c0e282b72d300f1, []int{1}
}
func (m *SignerPQCSignature) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignerPQCSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignerPQCSignature.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignerPQCSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignerPQCSignature.Merge(m, src)
}
func (m *SignerPQCSignature) XXX_Size() int {
	return m.Size()
}
func (m *SignerPQCSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_SignerPQCSignature.DiscardUnknown(m)
}

var xxx_messageInfo_SignerPQCSignature proto.InternalMessageInfo

func (m *SignerPQCSignature) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *SignerPQCSignature) GetSignerIndex() uint32 {
	if m != nil {
		return m.SignerIndex
	}
	return 0
}

func (m *SignerPQCSignature) GetKeyId() uint64 {
	if m != nil {
		return m.KeyId
	}
	return 0
}

func (m *SignerPQCSignature) GetAlgorithm() Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (m *SignerPQCSignature) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *SignerPQCSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ExtensionPQCAuth)(nil), "doravota.pqcauth.v1.ExtensionPQCAuth")
	proto.RegisterType((*SignerPQCSignature)(nil), "doravota.pqcauth.v1.SignerPQCSignature")
}

func init() {
	proto.RegisterFile("doravota/pqcauth/v1/extension.proto", fileDescriptor_9c0e282b72d300f1)
}

var fileDescriptor_9c0e282b72d300f1 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0xae, 0x9a, 0x40,
	0x18, 0xc5, 0x99, 0x7b, 0xbd, 0x24, 0x8e, 0x7f, 0xd2, 0x4c, 0xff, 0x84, 0x98, 0x66, 0xa4, 0x36,
	0x4d, 0x59, 0x41, 0xb4, 0xdb, 0x6e, 0xd4, 0xb6, 0x89, 0x0b, 0x13, 0xc5, 0xa4, 0x8b, 0x6e, 0xcc,
	0x08, 0x53, 0x98, 0xa8, 0x0c, 0x1d, 0x06, 0x22, 0x6f, 0xd0, 0x65, 0x1f, 0xa3, 0x8f, 0xe2, 0xd2,
	0x65, 0x57, 0x4d, 0x83, 0xab, 0xbe, 0x45, 0x03, 0x08, 0x36, 0xb9, 0xee, 0x3e, 0x7e, 0x9c, 0xef,
	0xcb, 0x99, 0x73, 0xe0, 0x6b, 0x97, 0x0b, 0x92, 0x70, 0x49, 0xac, 0xf0, 0x9b, 0x43, 0x62, 0xe9,
	0x5b, 0xc9, 0xd0, 0xa2, 0x07, 0x49, 0x83, 0x88, 0xf1, 0xc0, 0x0c, 0x05, 0x97, 0x1c, 0x3d, 0xad,
	0x44, 0xe6, 0x45, 0x64, 0x26, 0xc3, 0x5e, 0xff, 0xd6, 0x66, 0x24, 0x89, 0xa4, 0xe5, 0x56, 0xef,
	0x99, 0xc7, 0x3d, 0x5e, 0x8c, 0x56, 0x3e, 0x95, 0x74, 0xf0, 0x1d, 0xc0, 0x27, 0x1f, 0xab, 0xfb,
	0x8b, 0xe5, 0x74, 0x1c, 0x4b, 0x1f, 0xbd, 0x81, 0xdd, 0xaf, 0x5c, 0xec, 0x89, 0x5c, 0x27, 0x54,
	0xe4, 0x3f, 0x34, 0xa0, 0x03, 0xa3, 0x63, 0x77, 0x4a, 0xfa, 0xb9, 0x84, 0x68, 0x0e, 0x61, 0xc4,
	0xbc, 0x80, 0xc8, 0x58, 0xd0, 0x48, 0xbb, 0xd3, 0xef, 0x8d, 0xd6, 0xe8, 0xad, 0x79, 0xc3, 0x9c,
	0xb9, 0x62, 0x5e, 0x40, 0xc5, 0x62, 0x39, 0x5d, 0x55, 0xfa, 0x49, 0xe3, 0xf8, 0xbb, 0xaf, 0xd8,
	0xff, 0x1d, 0x18, 0xfc, 0x05, 0x10, 0x3d, 0x16, 0xa2, 0x17, 0x50, 0x8d, 0x0a, 0x5a, 0x98, 0x68,
	0xda, 0x97, 0x2f, 0xf4, 0x0a, 0xb6, 0xcb, 0x69, 0xcd, 0x02, 0x97, 0x1e, 0xb4, 0xbb, 0xc2, 0x62,
	0xab, 0x64, 0xb3, 0x1c, 0xa1, 0xe7, 0x50, 0xdd, 0xd2, 0x74, 0xcd, 0x5c, 0xed, 0x5e, 0x07, 0x46,
	0xc3, 0x7e, 0xd8, 0xd2, 0x74, 0xe6, 0xa2, 0xf7, 0xb0, 0x49, 0x76, 0x1e, 0x17, 0x4c, 0xfa, 0x7b,
	0xad, 0xa1, 0x03, 0xa3, 0x3b, 0xc2, 0x37, 0x6d, 0x8f, 0x2b, 0x95, 0x7d, 0x5d, 0xc8, 0xc3, 0x09,
	0xf9, 0x8e, 0x39, 0x69, 0x1d, 0xce, 0x43, 0x71, 0xbc, 0x53, 0xd2, 0x2a, 0x9c, 0x97, 0xb0, 0x59,
	0xbf, 0x4d, 0x53, 0x75, 0x60, 0xb4, 0xed, 0x2b, 0x98, 0xcc, 0x7f, 0x66, 0x18, 0x1c, 0x33, 0x0c,
	0x4e, 0x19, 0x06, 0x7f, 0x32, 0x0c, 0x7e, 0x9c, 0xb1, 0x72, 0x3a, 0x63, 0xe5, 0xd7, 0x19, 0x2b,
	0x5f, 0x2c, 0x8f, 0x49, 0x3f, 0xde, 0x98, 0x0e, 0xdf, 0x5b, 0x1f, 0xb8, 0x20, 0x9f, 0x88, 0x23,
	0xb9, 0x48, 0xad, 0xba, 0xe2, 0x43, 0x5d, 0xb2, 0x4c, 0x43, 0x1a, 0x6d, 0xd4, 0xa2, 0xcc, 0x77,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x25, 0x42, 0x77, 0x3f, 0x02, 0x00, 0x00,
}

func (this *ExtensionPQCAuth) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExtensionPQCAuth)
	if !ok {
		that2, ok := that.(ExtensionPQCAuth)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatVersion != that1.FormatVersion {
		return false
	}
	if len(this.Signatures) != len(that1.Signatures) {
		return false
	}
	for i := range this.Signatures {
		if !this.Signatures[i].Equal(&that1.Signatures[i]) {
			return false
		}
	}
	return true
}
func (this *SignerPQCSignature) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SignerPQCSignature)
	if !ok {
		that2, ok := that.(SignerPQCSignature)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Signer != that1.Signer {
		return false
	}
	if this.SignerIndex != that1.SignerIndex {
		return false
	}
	if this.KeyId != that1.KeyId {
		return false
	}
	if this.Algorithm != that1.Algorithm {
		return false
	}
	if this.PolicyVersion != that1.PolicyVersion {
		return false
	}
	if !bytes.Equal(this.Signature, that1.Signature) {
		return false
	}
	return true
}
func (m *ExtensionPQCAuth) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExtensionPQCAuth) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExtensionPQCAuth) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signatures[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintExtension(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.FormatVersion != 0 {
		i = encodeVarintExtension(dAtA, i, uint64(m.FormatVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SignerPQCSignature) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignerPQCSignature) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignerPQCSignature) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintExtension(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x32
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintExtension(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x28
	}
	if m.Algorithm != 0 {
		i = encodeVarintExtension(dAtA, i, uint64(m.Algorithm))
		i--
		dAtA[i] = 0x20
	}
	if m.KeyId != 0 {
		i = encodeVarintExtension(dAtA, i, uint64(m.KeyId))
		i--
		dAtA[i] = 0x18
	}
	if m.SignerIndex != 0 {
		i = encodeVarintExtension(dAtA, i, uint64(m.SignerIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintExtension(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintExtension(dAtA []byte, offset int, v uint64) int {
	offset -= sovExtension(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ExtensionPQCAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FormatVersion != 0 {
		n += 1 + sovExtension(uint64(m.FormatVersion))
	}
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovExtension(uint64(l))
		}
	}
	return n
}

func (m *SignerPQCSignature) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovExtension(uint64(l))
	}
	if m.SignerIndex != 0 {
		n += 1 + sovExtension(uint64(m.SignerIndex))
	}
	if m.KeyId != 0 {
		n += 1 + sovExtension(uint64(m.KeyId))
	}
	if m.Algorithm != 0 {
		n += 1 + sovExtension(uint64(m.Algorithm))
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovExtension(uint64(m.PolicyVersion))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovExtension(uint64(l))
	}
	return n
}

func sovExtension(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExtension(x uint64) (n int) {
	return sovExtension(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ExtensionPQCAuth) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExtension
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExtensionPQCAuth: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExtensionPQCAuth: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatVersion", wireType)
			}
			m.FormatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FormatVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExtension
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signatures = append(m.Signatures, SignerPQCSignature{})
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExtension(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExtension
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignerPQCSignature) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExtension
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignerPQCSignature: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignerPQCSignature: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExtension
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerIndex", wireType)
			}
			m.SignerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyId", wireType)
			}
			m.KeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algorithm", wireType)
			}
			m.Algorithm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Algorithm |= Algorithm(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthExtension
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExtension(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExtension
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExtension(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExtension
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExtension
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExtension
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExtension
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExtension
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExtension        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExtension          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExtension = fmt.Errorf("proto: unexpected end of group")
)
