// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doravota/pqcauth/v1/signing.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PQCSignDocV1 is the canonical payload signed by one transaction signer.
// body_bytes_without_pqc_auth is the deterministic TxBody encoding after
// removing the pqcauth extension while preserving every other body field.
type PQCSignDocV1 struct {
	FormatVersion           uint32    `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	NetworkId               []byte    `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChainId                 string    `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AccountNumber           uint64    `protobuf:"varint,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence                uint64    `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SignerIndex             uint32    `protobuf:"varint,6,opt,name=signer_index,json=signerIndex,proto3" json:"signer_index,omitempty"`
	Signer                  string    `protobuf:"bytes,7,opt,name=signer,proto3" json:"signer,omitempty"`
	KeyId                   uint64    `protobuf:"varint,8,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm               Algorithm `protobuf:"varint,9,opt,name=algorithm,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"algorithm,omitempty"`
	PolicyVersion           uint64    `protobuf:"varint,10,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	BodyBytesWithoutPqcAuth []byte    `protobuf:"bytes,11,opt,name=body_bytes_without_pqc_auth,json=bodyBytesWithoutPqcAuth,proto3" json:"body_bytes_without_pqc_auth,omitempty"`
	AuthInfoBytes           []byte    `protobuf:"bytes,12,opt,name=auth_info_bytes,json=authInfoBytes,proto3" json:"auth_info_bytes,omitempty"`
}

func (m *PQCSignDocV1) Reset()         { *m = PQCSignDocV1{} }
func (m *PQCSignDocV1) String() string { return proto.CompactTextString(m) }
func (*PQCSignDocV1) ProtoMessage()    {}
func (*PQCSignDocV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_12084ca9c4ac24c9, []int{0}
}
func (m *PQCSignDocV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PQCSignDocV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PQCSignDocV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PQCSignDocV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQCSignDocV1.Merge(m, src)
}
func (m *PQCSignDocV1) XXX_Size() int {
	return m.Size()
}
func (m *PQCSignDocV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PQCSignDocV1.DiscardUnknown(m)
}

var xxx_messageInfo_PQCSignDocV1 proto.InternalMessageInfo

func (m *PQCSignDocV1) GetFormatVersion() uint32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

func (m *PQCSignDocV1) GetNetworkId() []byte {
	if m != nil {
		return m.NetworkId
	}
	return nil
}

func (m *PQCSignDocV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *PQCSignDocV1) GetAccountNumber() uint64 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *PQCSignDocV1) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PQCSignDocV1) GetSignerIndex() uint32 {
	if m != nil {
		return m.SignerIndex
	}
	return 0
}

func (m *PQCSignDocV1) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *PQCSignDocV1) GetKeyId() uint64 {
	if m != nil {
		return m.KeyId
	}
	return 0
}

func (m *PQCSignDocV1) GetAlgorithm() Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (m *PQCSignDocV1) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *PQCSignDocV1) GetBodyBytesWithoutPqcAuth() []byte {
	if m != nil {
		return m.BodyBytesWithoutPqcAuth
	}
	return nil
}

func (m *PQCSignDocV1) GetAuthInfoBytes() []byte {
	if m != nil {
		return m.AuthInfoBytes
	}
	return nil
}

// KeyProofDocV1 is signed by a proposed key to prove possession before the key
// is stored. purpose domain-separates registration, rotation, and recovery.
type KeyProofDocV1 struct {
	FormatVersion        uint32    `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	NetworkId            []byte    `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChainId              string    `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Owner                string    `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ProposedKeyId        uint64    `protobuf:"varint,5,opt,name=proposed_key_id,json=proposedKeyId,proto3" json:"proposed_key_id,omitempty"`
	Algorithm            Algorithm `protobuf:"varint,6,opt,name=algorithm,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"algorithm,omitempty"`
	PublicKey            []byte    `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Role                 KeyRole   `protobuf:"varint,8,opt,name=role,proto3,enum=doravota.pqcauth.v1.KeyRole" json:"role,omitempty"`
	Purpose              string    `protobuf:"bytes,9,opt,name=purpose,proto3" json:"purpose,omitempty"`
	CurrentPolicyVersion uint64    `protobuf:"varint,10,opt,name=current_policy_version,json=currentPolicyVersion,proto3" json:"current_policy_version,omitempty"`
}

func (m *KeyProofDocV1) Reset()         { *m = KeyProofDocV1{} }
func (m *KeyProofDocV1) String() string { return proto.CompactTextString(m) }
func (*KeyProofDocV1) ProtoMessage()    {}
func (*KeyProofDocV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_12084ca9c4ac24c9, []int{1}
}
func (m *KeyProofDocV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyProofDocV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyProofDocV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyProofDocV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyProofDocV1.Merge(m, src)
}
func (m *KeyProofDocV1) XXX_Size() int {
	return m.Size()
}
func (m *KeyProofDocV1) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyProofDocV1.DiscardUnknown(m)
}

var xxx_messageInfo_KeyProofDocV1 proto.InternalMessageInfo

func (m *KeyProofDocV1) GetFormatVersion() uint32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

func (m *KeyProofDocV1) GetNetworkId() []byte {
	if m != nil {
		return m.NetworkId
	}
	return nil
}

func (m *KeyProofDocV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *KeyProofDocV1) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *KeyProofDocV1) GetProposedKeyId() uint64 {
	if m != nil {
		return m.ProposedKeyId
	}
	return 0
}

func (m *KeyProofDocV1) GetAlgorithm() Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (m *KeyProofDocV1) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *KeyProofDocV1) GetRole() KeyRole {
	if m != nil {
		return m.Role
	}
	return KeyRole_KEY_ROLE_UNSPECIFIED
}

func (m *KeyProofDocV1) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *KeyProofDocV1) GetCurrentPolicyVersion() uint64 {
	if m != nil {
		return m.CurrentPolicyVersion
	}
	return 0
}

// RecoverySignDocV1 is authorized by the registered recovery key. It binds the
// replacement key and the complete transaction intent. The recovery signature
// field inside body_bytes_without_pqc_auth_and_recovery_signature is cleared
// before deterministic encoding to avoid a circular signature dependency.
type RecoverySignDocV1 struct {
	FormatVersion                               uint32    `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	NetworkId                                   []byte    `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChainId                                     string    `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Owner                                       string    `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	RecoveryKeyId                               uint64    `protobuf:"varint,5,opt,name=recovery_key_id,json=recoveryKeyId,proto3" json:"recovery_key_id,omitempty"`
	ProposedSigningKeyId                        uint64    `protobuf:"varint,6,opt,name=proposed_signing_key_id,json=proposedSigningKeyId,proto3" json:"proposed_signing_key_id,omitempty"`
	ProposedAlgorithm                           Algorithm `protobuf:"varint,7,opt,name=proposed_algorithm,json=proposedAlgorithm,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"proposed_algorithm,omitempty"`
	ProposedPublicKey                           []byte    `protobuf:"bytes,8,opt,name=proposed_public_key,json=proposedPublicKey,proto3" json:"proposed_public_key,omitempty"`
	CurrentPolicyVersion                        uint64    `protobuf:"varint,9,opt,name=current_policy_version,json=currentPolicyVersion,proto3" json:"current_policy_version,omitempty"`
	AccountNumber                               uint64    `protobuf:"varint,10,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Sequence                                    uint64    `protobuf:"varint,11,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SignerIndex                                 uint32    `protobuf:"varint,12,opt,name=signer_index,json=signerIndex,proto3" json:"signer_index,omitempty"`
	Signer                                      string    `protobuf:"bytes,13,opt,name=signer,proto3" json:"signer,omitempty"`
	BodyBytesWithoutPqcAuthAndRecoverySignature []byte    `protobuf:"bytes,14,opt,name=body_bytes_without_pqc_auth_and_recovery_signature,json=bodyBytesWithoutPqcAuthAndRecoverySignature,proto3" json:"body_bytes_without_pqc_auth_and_recovery_signature,omitempty"`
	AuthInfoBytes                               []byte    `protobuf:"bytes,15,opt,name=auth_info_bytes,json=authInfoBytes,proto3" json:"auth_info_bytes,omitempty"`
}

func (m *RecoverySignDocV1) Reset()         { *m = RecoverySignDocV1{} }
func (m *RecoverySignDocV1) String() string { return proto.CompactTextString(m) }
func (*RecoverySignDocV1) ProtoMessage()    {}
func (*RecoverySignDocV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_12084ca9c4ac24c9, []int{2}
}
func (m *RecoverySignDocV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RecoverySignDocV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RecoverySignDocV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RecoverySignDocV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverySignDocV1.Merge(m, src)
}
func (m *RecoverySignDocV1) XXX_Size() int {
	return m.Size()
}
func (m *RecoverySignDocV1) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverySignDocV1.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverySignDocV1 proto.InternalMessageInfo

func (m *RecoverySignDocV1) GetFormatVersion() uint32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

func (m *RecoverySignDocV1) GetNetworkId() []byte {
	if m != nil {
		return m.NetworkId
	}
	return nil
}

func (m *RecoverySignDocV1) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *RecoverySignDocV1) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RecoverySignDocV1) GetRecoveryKeyId() uint64 {
	if m != nil {
		return m.RecoveryKeyId
	}
	return 0
}

func (m *RecoverySignDocV1) GetProposedSigningKeyId() uint64 {
	if m != nil {
		return m.ProposedSigningKeyId
	}
	return 0
}

func (m *RecoverySignDocV1) GetProposedAlgorithm() Algorithm {
	if m != nil {
		return m.ProposedAlgorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (m *RecoverySignDocV1) GetProposedPublicKey() []byte {
	if m != nil {
		return m.ProposedPublicKey
	}
	return nil
}

func (m *RecoverySignDocV1) GetCurrentPolicyVersion() uint64 {
	if m != nil {
		return m.CurrentPolicyVersion
	}
	return 0
}

func (m *RecoverySignDocV1) GetAccountNumber() uint64 {
	if m != nil {
		return m.AccountNumber
	}
	return 0
}

func (m *RecoverySignDocV1) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *RecoverySignDocV1) GetSignerIndex() uint32 {
	if m != nil {
		return m.SignerIndex
	}
	return 0
}

func (m *RecoverySignDocV1) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *RecoverySignDocV1) GetBodyBytesWithoutPqcAuthAndRecoverySignature() []byte {
	if m != nil {
		return m.BodyBytesWithoutPqcAuthAndRecoverySignature
	}
	return nil
}

func (m *RecoverySignDocV1) GetAuthInfoBytes() []byte {
	if m != nil {
		return m.AuthInfoBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*PQCSignDocV1)(nil), "doravota.pqcauth.v1.PQCSignDocV1")
	proto.RegisterType((*KeyProofDocV1)(nil), "doravota.pqcauth.v1.KeyProofDocV1")
	proto.RegisterType((*RecoverySignDocV1)(nil), "doravota.pqcauth.v1.RecoverySignDocV1")
}

func init() { proto.RegisterFile("doravota/pqcauth/v1/signing.proto", fileDescriptor_12084ca9c4ac24c9) }

var fileDescriptor_12084ca9c4ac24c9 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x4e, 0xdb, 0x4a,
	0x18, 0xc5, 0x17, 0xf2, 0xe3, 0x21, 0x09, 0x62, 0xe0, 0x82, 0x2f, 0xf7, 0xe2, 0x1b, 0x90, 0x5a,
	0x45, 0xaa, 0x94, 0x14, 0xda, 0xee, 0xd8, 0x40, 0x51, 0xa5, 0x28, 0xa2, 0x4a, 0x8d, 0x44, 0xa5,
	0x6e, 0x2c, 0xc7, 0x9e, 0x38, 0x16, 0xc9, 0x7c, 0xce, 0x64, 0x1c, 0xf0, 0x43, 0x54, 0xea, 0x63,
	0x74, 0xd3, 0xf7, 0xe8, 0xae, 0x2c, 0xbb, 0xac, 0xc2, 0x8b, 0x54, 0x33, 0x63, 0x1b, 0xda, 0x3a,
	0xd0, 0x6e, 0xd8, 0xe5, 0x3b, 0x73, 0xbe, 0x99, 0x6f, 0xce, 0x71, 0xce, 0xa0, 0x1d, 0x0f, 0x98,
	0x33, 0x05, 0xee, 0xb4, 0xc2, 0xb1, 0xeb, 0x44, 0x7c, 0xd0, 0x9a, 0xee, 0xb5, 0x26, 0x81, 0x4f,
	0x03, 0xea, 0x37, 0x43, 0x06, 0x1c, 0xf0, 0x5a, 0x4a, 0x69, 0x26, 0x94, 0xe6, 0x74, 0x6f, 0xeb,
	0xff, 0xdc, 0x3e, 0xee, 0x70, 0xa2, 0xba, 0xb6, 0xd6, 0x7d, 0xf0, 0x41, 0xfe, 0x6c, 0x89, 0x5f,
	0x0a, 0xdd, 0xfd, 0xb2, 0x88, 0x2a, 0xdd, 0x37, 0x2f, 0x4f, 0x03, 0x9f, 0x1e, 0x83, 0x7b, 0xb6,
	0x87, 0x1f, 0xa1, 0x5a, 0x1f, 0xd8, 0xc8, 0xe1, 0xf6, 0x94, 0xb0, 0x49, 0x00, 0xd4, 0xd0, 0xea,
	0x5a, 0xa3, 0x6a, 0x55, 0x15, 0x7a, 0xa6, 0x40, 0xbc, 0x8d, 0x10, 0x25, 0xfc, 0x02, 0xd8, 0xb9,
	0x1d, 0x78, 0xc6, 0x5f, 0x75, 0xad, 0x51, 0xb1, 0xf4, 0x04, 0x69, 0x7b, 0xf8, 0x1f, 0x54, 0x76,
	0x07, 0x4e, 0x40, 0xc5, 0xe2, 0x62, 0x5d, 0x6b, 0xe8, 0x56, 0x49, 0xd6, 0x6d, 0x4f, 0x1c, 0xe0,
	0xb8, 0x2e, 0x44, 0x94, 0xdb, 0x34, 0x1a, 0xf5, 0x08, 0x33, 0x96, 0xea, 0x5a, 0x63, 0xc9, 0xaa,
	0x26, 0xe8, 0x6b, 0x09, 0xe2, 0x2d, 0x54, 0x9e, 0x90, 0x71, 0x44, 0xa8, 0x4b, 0x8c, 0x82, 0x24,
	0x64, 0x35, 0xde, 0x41, 0x15, 0xa1, 0x08, 0x61, 0x76, 0x40, 0x3d, 0x72, 0x69, 0x14, 0xe5, 0x84,
	0xcb, 0x0a, 0x6b, 0x0b, 0x08, 0x6f, 0xa0, 0xa2, 0x2a, 0x8d, 0x92, 0x3c, 0x3e, 0xa9, 0xf0, 0xdf,
	0xa8, 0x78, 0x4e, 0x62, 0x31, 0x56, 0x59, 0x6e, 0x5a, 0x38, 0x27, 0x71, 0xdb, 0xc3, 0x07, 0x48,
	0x77, 0x86, 0x3e, 0xb0, 0x80, 0x0f, 0x46, 0x86, 0x5e, 0xd7, 0x1a, 0xb5, 0x7d, 0xb3, 0x99, 0x23,
	0x73, 0xf3, 0x30, 0x65, 0x59, 0x37, 0x0d, 0xe2, 0x4a, 0x21, 0x0c, 0x03, 0x37, 0xce, 0x34, 0x43,
	0xea, 0x4a, 0x0a, 0x4d, 0x35, 0x3b, 0x40, 0xff, 0xf6, 0xc0, 0x8b, 0xed, 0x5e, 0xcc, 0xc9, 0xc4,
	0xbe, 0x08, 0xf8, 0x00, 0x22, 0x6e, 0x87, 0x63, 0xd7, 0x16, 0xbb, 0x1b, 0xcb, 0x52, 0xc4, 0x4d,
	0x41, 0x39, 0x12, 0x8c, 0xb7, 0x8a, 0xd0, 0x1d, 0xbb, 0x87, 0x11, 0x1f, 0xe0, 0xc7, 0x68, 0x45,
	0xd0, 0xec, 0x80, 0xf6, 0x41, 0x6d, 0x61, 0x54, 0x64, 0x47, 0x55, 0xc0, 0x6d, 0xda, 0x07, 0xd9,
	0xb5, 0xfb, 0x7e, 0x11, 0x55, 0x3b, 0x24, 0xee, 0x32, 0x80, 0xfe, 0x03, 0x59, 0xba, 0x8e, 0x0a,
	0x70, 0x41, 0x13, 0x27, 0x75, 0x4b, 0x15, 0x62, 0xe0, 0x90, 0x41, 0x08, 0x13, 0xe2, 0xd9, 0x89,
	0xe6, 0x85, 0x44, 0x96, 0x04, 0xee, 0xfc, 0xaa, 0x7d, 0xf1, 0x4f, 0xb5, 0xdf, 0x46, 0x28, 0x8c,
	0x7a, 0xc3, 0xc0, 0x15, 0x67, 0x48, 0xb3, 0x2b, 0x96, 0xae, 0x90, 0x0e, 0x89, 0xf1, 0x53, 0xb4,
	0xc4, 0x60, 0x48, 0xa4, 0xdb, 0xb5, 0xfd, 0xff, 0x72, 0xf7, 0xed, 0x90, 0xd8, 0x82, 0x21, 0xb1,
	0x24, 0x13, 0x1b, 0xa8, 0x14, 0x46, 0x4c, 0xcc, 0x27, 0x3f, 0x04, 0xdd, 0x4a, 0x4b, 0xfc, 0x1c,
	0x6d, 0xb8, 0x11, 0x63, 0x84, 0x72, 0x3b, 0xd7, 0xee, 0xf5, 0x64, 0xb5, 0x7b, 0xdb, 0xf5, 0xdd,
	0x4f, 0x05, 0xb4, 0x6a, 0x11, 0x17, 0xa6, 0x84, 0xc5, 0x0f, 0xf8, 0x37, 0x9b, 0xeb, 0x09, 0x4b,
	0x66, 0xf9, 0xc9, 0x93, 0x14, 0x56, 0x9e, 0xbc, 0x40, 0x9b, 0x99, 0x77, 0x49, 0xf8, 0xa4, 0xfc,
	0xa2, 0xba, 0x6b, 0xba, 0x7c, 0xaa, 0x56, 0x55, 0xdb, 0x09, 0xc2, 0x59, 0xdb, 0x8d, 0xa7, 0xa5,
	0xdf, 0xf2, 0x74, 0x35, 0xed, 0xcc, 0x20, 0xdc, 0x44, 0x6b, 0xd9, 0x76, 0xb7, 0x4c, 0x2e, 0x4b,
	0x19, 0x32, 0x7e, 0x37, 0x33, 0x7b, 0xbe, 0x41, 0xfa, 0x7c, 0x83, 0x72, 0x02, 0x09, 0xdd, 0x17,
	0x48, 0xcb, 0xf7, 0x04, 0x52, 0xe5, 0xae, 0x40, 0xaa, 0xfe, 0x10, 0x48, 0x3e, 0xda, 0xbf, 0x23,
	0x14, 0x6c, 0x87, 0x7a, 0x76, 0xe6, 0x98, 0x68, 0x71, 0x78, 0xc4, 0x88, 0x51, 0x93, 0x12, 0x3c,
	0x99, 0x93, 0x15, 0x87, 0xd4, 0xbb, 0xfd, 0xc5, 0xc9, 0x96, 0xbc, 0xfc, 0x58, 0xc9, 0xc9, 0x8f,
	0xa3, 0x93, 0x8f, 0x33, 0x53, 0xfb, 0x3c, 0x33, 0xb5, 0xab, 0x99, 0xa9, 0x7d, 0x9b, 0x99, 0xda,
	0x87, 0x6b, 0x73, 0xe1, 0xea, 0xda, 0x5c, 0xf8, 0x7a, 0x6d, 0x2e, 0xbc, 0x6b, 0xf9, 0x01, 0x1f,
	0x44, 0xbd, 0xa6, 0x0b, 0xa3, 0xd6, 0x31, 0x30, 0xe7, 0x95, 0xe3, 0x72, 0x60, 0x71, 0x2b, 0x7b,
	0x7d, 0x2e, 0xb3, 0xf7, 0x87, 0xc7, 0x21, 0x99, 0xf4, 0x8a, 0xf2, 0x9d, 0x79, 0xf6, 0x3d, 0x00,
	0x00, 0xff, 0xff, 0x36, 0xc7, 0x93, 0x15, 0xd8, 0x06, 0x00, 0x00,
}

func (this *PQCSignDocV1) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PQCSignDocV1)
	if !ok {
		that2, ok := that.(PQCSignDocV1)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatVersion != that1.FormatVersion {
		return false
	}
	if !bytes.Equal(this.NetworkId, that1.NetworkId) {
		return false
	}
	if this.ChainId != that1.ChainId {
		return false
	}
	if this.AccountNumber != that1.AccountNumber {
		return false
	}
	if this.Sequence != that1.Sequence {
		return false
	}
	if this.SignerIndex != that1.SignerIndex {
		return false
	}
	if this.Signer != that1.Signer {
		return false
	}
	if this.KeyId != that1.KeyId {
		return false
	}
	if this.Algorithm != that1.Algorithm {
		return false
	}
	if this.PolicyVersion != that1.PolicyVersion {
		return false
	}
	if !bytes.Equal(this.BodyBytesWithoutPqcAuth, that1.BodyBytesWithoutPqcAuth) {
		return false
	}
	if !bytes.Equal(this.AuthInfoBytes, that1.AuthInfoBytes) {
		return false
	}
	return true
}
func (this *KeyProofDocV1) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*KeyProofDocV1)
	if !ok {
		that2, ok := that.(KeyProofDocV1)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatVersion != that1.FormatVersion {
		return false
	}
	if !bytes.Equal(this.NetworkId, that1.NetworkId) {
		return false
	}
	if this.ChainId != that1.ChainId {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.ProposedKeyId != that1.ProposedKeyId {
		return false
	}
	if this.Algorithm != that1.Algorithm {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if this.Role != that1.Role {
		return false
	}
	if this.Purpose != that1.Purpose {
		return false
	}
	if this.CurrentPolicyVersion != that1.CurrentPolicyVersion {
		return false
	}
	return true
}
func (this *RecoverySignDocV1) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RecoverySignDocV1)
	if !ok {
		that2, ok := that.(RecoverySignDocV1)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FormatVersion != that1.FormatVersion {
		return false
	}
	if !bytes.Equal(this.NetworkId, that1.NetworkId) {
		return false
	}
	if this.ChainId != that1.ChainId {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.RecoveryKeyId != that1.RecoveryKeyId {
		return false
	}
	if this.ProposedSigningKeyId != that1.ProposedSigningKeyId {
		return false
	}
	if this.ProposedAlgorithm != that1.ProposedAlgorithm {
		return false
	}
	if !bytes.Equal(this.ProposedPublicKey, that1.ProposedPublicKey) {
		return false
	}
	if this.CurrentPolicyVersion != that1.CurrentPolicyVersion {
		return false
	}
	if this.AccountNumber != that1.AccountNumber {
		return false
	}
	if this.Sequence != that1.Sequence {
		return false
	}
	if this.SignerIndex != that1.SignerIndex {
		return false
	}
	if this.Signer != that1.Signer {
		return false
	}
	if !bytes.Equal(this.BodyBytesWithoutPqcAuthAndRecoverySignature, that1.BodyBytesWithoutPqcAuthAndRecoverySignature) {
		return false
	}
	if !bytes.Equal(this.AuthInfoBytes, that1.AuthInfoBytes) {
		return false
	}
	return true
}
func (m *PQCSignDocV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PQCSignDocV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PQCSignDocV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuthInfoBytes) > 0 {
		i -= len(m.AuthInfoBytes)
		copy(dAtA[i:], m.AuthInfoBytes)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.AuthInfoBytes)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.BodyBytesWithoutPqcAuth) > 0 {
		i -= len(m.BodyBytesWithoutPqcAuth)
		copy(dAtA[i:], m.BodyBytesWithoutPqcAuth)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.BodyBytesWithoutPqcAuth)))
		i--
		dAtA[i] = 0x5a
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x50
	}
	if m.Algorithm != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.Algorithm))
		i--
		dAtA[i] = 0x48
	}
	if m.KeyId != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.KeyId))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SignerIndex != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.SignerIndex))
		i--
		dAtA[i] = 0x30
	}
	if m.Sequence != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x28
	}
	if m.AccountNumber != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.AccountNumber))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NetworkId) > 0 {
		i -= len(m.NetworkId)
		copy(dAtA[i:], m.NetworkId)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.NetworkId)))
		i--
		dAtA[i] = 0x12
	}
	if m.FormatVersion != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.FormatVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *KeyProofDocV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyProofDocV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyProofDocV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentPolicyVersion != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.CurrentPolicyVersion))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Purpose) > 0 {
		i -= len(m.Purpose)
		copy(dAtA[i:], m.Purpose)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.Purpose)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Role != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x40
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Algorithm != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.Algorithm))
		i--
		dAtA[i] = 0x30
	}
	if m.ProposedKeyId != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.ProposedKeyId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NetworkId) > 0 {
		i -= len(m.NetworkId)
		copy(dAtA[i:], m.NetworkId)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.NetworkId)))
		i--
		dAtA[i] = 0x12
	}
	if m.FormatVersion != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.FormatVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RecoverySignDocV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RecoverySignDocV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RecoverySignDocV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuthInfoBytes) > 0 {
		i -= len(m.AuthInfoBytes)
		copy(dAtA[i:], m.AuthInfoBytes)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.AuthInfoBytes)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.BodyBytesWithoutPqcAuthAndRecoverySignature) > 0 {
		i -= len(m.BodyBytesWithoutPqcAuthAndRecoverySignature)
		copy(dAtA[i:], m.BodyBytesWithoutPqcAuthAndRecoverySignature)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.BodyBytesWithoutPqcAuthAndRecoverySignature)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x6a
	}
	if m.SignerIndex != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.SignerIndex))
		i--
		dAtA[i] = 0x60
	}
	if m.Sequence != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x58
	}
	if m.AccountNumber != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.AccountNumber))
		i--
		dAtA[i] = 0x50
	}
	if m.CurrentPolicyVersion != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.CurrentPolicyVersion))
		i--
		dAtA[i] = 0x48
	}
	if len(m.ProposedPublicKey) > 0 {
		i -= len(m.ProposedPublicKey)
		copy(dAtA[i:], m.ProposedPublicKey)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.ProposedPublicKey)))
		i--
		dAtA[i] = 0x42
	}
	if m.ProposedAlgorithm != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.ProposedAlgorithm))
		i--
		dAtA[i] = 0x38
	}
	if m.ProposedSigningKeyId != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.ProposedSigningKeyId))
		i--
		dAtA[i] = 0x30
	}
	if m.RecoveryKeyId != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.RecoveryKeyId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NetworkId) > 0 {
		i -= len(m.NetworkId)
		copy(dAtA[i:], m.NetworkId)
		i = encodeVarintSigning(dAtA, i, uint64(len(m.NetworkId)))
		i--
		dAtA[i] = 0x12
	}
	if m.FormatVersion != 0 {
		i = encodeVarintSigning(dAtA, i, uint64(m.FormatVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSigning(dAtA []byte, offset int, v uint64) int {
	offset -= sovSigning(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PQCSignDocV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FormatVersion != 0 {
		n += 1 + sovSigning(uint64(m.FormatVersion))
	}
	l = len(m.NetworkId)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.AccountNumber != 0 {
		n += 1 + sovSigning(uint64(m.AccountNumber))
	}
	if m.Sequence != 0 {
		n += 1 + sovSigning(uint64(m.Sequence))
	}
	if m.SignerIndex != 0 {
		n += 1 + sovSigning(uint64(m.SignerIndex))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.KeyId != 0 {
		n += 1 + sovSigning(uint64(m.KeyId))
	}
	if m.Algorithm != 0 {
		n += 1 + sovSigning(uint64(m.Algorithm))
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovSigning(uint64(m.PolicyVersion))
	}
	l = len(m.BodyBytesWithoutPqcAuth)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.AuthInfoBytes)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	return n
}

func (m *KeyProofDocV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FormatVersion != 0 {
		n += 1 + sovSigning(uint64(m.FormatVersion))
	}
	l = len(m.NetworkId)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.ProposedKeyId != 0 {
		n += 1 + sovSigning(uint64(m.ProposedKeyId))
	}
	if m.Algorithm != 0 {
		n += 1 + sovSigning(uint64(m.Algorithm))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovSigning(uint64(m.Role))
	}
	l = len(m.Purpose)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.CurrentPolicyVersion != 0 {
		n += 1 + sovSigning(uint64(m.CurrentPolicyVersion))
	}
	return n
}

func (m *RecoverySignDocV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FormatVersion != 0 {
		n += 1 + sovSigning(uint64(m.FormatVersion))
	}
	l = len(m.NetworkId)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.RecoveryKeyId != 0 {
		n += 1 + sovSigning(uint64(m.RecoveryKeyId))
	}
	if m.ProposedSigningKeyId != 0 {
		n += 1 + sovSigning(uint64(m.ProposedSigningKeyId))
	}
	if m.ProposedAlgorithm != 0 {
		n += 1 + sovSigning(uint64(m.ProposedAlgorithm))
	}
	l = len(m.ProposedPublicKey)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	if m.CurrentPolicyVersion != 0 {
		n += 1 + sovSigning(uint64(m.CurrentPolicyVersion))
	}
	if m.AccountNumber != 0 {
		n += 1 + sovSigning(uint64(m.AccountNumber))
	}
	if m.Sequence != 0 {
		n += 1 + sovSigning(uint64(m.Sequence))
	}
	if m.SignerIndex != 0 {
		n += 1 + sovSigning(uint64(m.SignerIndex))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.BodyBytesWithoutPqcAuthAndRecoverySignature)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	l = len(m.AuthInfoBytes)
	if l > 0 {
		n += 1 + l + sovSigning(uint64(l))
	}
	return n
}

func sovSigning(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSigning(x uint64) (n int) {
	return sovSigning(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PQCSignDocV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSigning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PQCSignDocV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PQCSignDocV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatVersion", wireType)
			}
			m.FormatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FormatVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkId = append(m.NetworkId[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkId == nil {
				m.NetworkId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountNumber", wireType)
			}
			m.AccountNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerIndex", wireType)
			}
			m.SignerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyId", wireType)
			}
			m.KeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algorithm", wireType)
			}
			m.Algorithm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Algorithm |= Algorithm(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyBytesWithoutPqcAuth", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BodyBytesWithoutPqcAuth = append(m.BodyBytesWithoutPqcAuth[:0], dAtA[iNdEx:postIndex]...)
			if m.BodyBytesWithoutPqcAuth == nil {
				m.BodyBytesWithoutPqcAuth = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthInfoBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthInfoBytes = append(m.AuthInfoBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.AuthInfoBytes == nil {
				m.AuthInfoBytes = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSigning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSigning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyProofDocV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSigning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyProofDocV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyProofDocV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatVersion", wireType)
			}
			m.FormatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FormatVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkId = append(m.NetworkId[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkId == nil {
				m.NetworkId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedKeyId", wireType)
			}
			m.ProposedKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposedKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algorithm", wireType)
			}
			m.Algorithm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Algorithm |= Algorithm(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= KeyRole(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPolicyVersion", wireType)
			}
			m.CurrentPolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentPolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSigning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSigning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RecoverySignDocV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSigning
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RecoverySignDocV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RecoverySignDocV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FormatVersion", wireType)
			}
			m.FormatVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FormatVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkId = append(m.NetworkId[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkId == nil {
				m.NetworkId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryKeyId", wireType)
			}
			m.RecoveryKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoveryKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedSigningKeyId", wireType)
			}
			m.ProposedSigningKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposedSigningKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedAlgorithm", wireType)
			}
			m.ProposedAlgorithm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposedAlgorithm |= Algorithm(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposedPublicKey = append(m.ProposedPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ProposedPublicKey == nil {
				m.ProposedPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPolicyVersion", wireType)
			}
			m.CurrentPolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentPolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountNumber", wireType)
			}
			m.AccountNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerIndex", wireType)
			}
			m.SignerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyBytesWithoutPqcAuthAndRecoverySignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BodyBytesWithoutPqcAuthAndRecoverySignature = append(m.BodyBytesWithoutPqcAuthAndRecoverySignature[:0], dAtA[iNdEx:postIndex]...)
			if m.BodyBytesWithoutPqcAuthAndRecoverySignature == nil {
				m.BodyBytesWithoutPqcAuthAndRecoverySignature = []byte{}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthInfoBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSigning
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSigning
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthInfoBytes = append(m.AuthInfoBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.AuthInfoBytes == nil {
				m.AuthInfoBytes = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSigning(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSigning
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSigning(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSigning
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSigning
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSigning
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSigning
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSigning
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSigning        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSigning          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSigning = fmt.Errorf("proto: unexpected end of group")
)
