// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: doravota/pqcauth/v1/state.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Algorithm identifies a post-quantum signature algorithm.
type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_ALGORITHM_ML_DSA_65   Algorithm = 1
)

var Algorithm_name = map[int32]string{
	0: "ALGORITHM_UNSPECIFIED",
	1: "ALGORITHM_ML_DSA_65",
}

var Algorithm_value = map[string]int32{
	"ALGORITHM_UNSPECIFIED": 0,
	"ALGORITHM_ML_DSA_65":   1,
}

func (x Algorithm) String() string {
	return proto.EnumName(Algorithm_name, int32(x))
}

func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{0}
}

// EnforcementMode controls which accounts must include valid PQC authorization.
type EnforcementMode int32

const (
	EnforcementMode_ENFORCEMENT_MODE_UNSPECIFIED             EnforcementMode = 0
	EnforcementMode_ENFORCEMENT_MODE_DISABLED                EnforcementMode = 1
	EnforcementMode_ENFORCEMENT_MODE_OPTIONAL                EnforcementMode = 2
	EnforcementMode_ENFORCEMENT_MODE_REQUIRED_FOR_REGISTERED EnforcementMode = 3
	EnforcementMode_ENFORCEMENT_MODE_REQUIRED                EnforcementMode = 4
)

var EnforcementMode_name = map[int32]string{
	0: "ENFORCEMENT_MODE_UNSPECIFIED",
	1: "ENFORCEMENT_MODE_DISABLED",
	2: "ENFORCEMENT_MODE_OPTIONAL",
	3: "ENFORCEMENT_MODE_REQUIRED_FOR_REGISTERED",
	4: "ENFORCEMENT_MODE_REQUIRED",
}

var EnforcementMode_value = map[string]int32{
	"ENFORCEMENT_MODE_UNSPECIFIED":             0,
	"ENFORCEMENT_MODE_DISABLED":                1,
	"ENFORCEMENT_MODE_OPTIONAL":                2,
	"ENFORCEMENT_MODE_REQUIRED_FOR_REGISTERED": 3,
	"ENFORCEMENT_MODE_REQUIRED":                4,
}

func (x EnforcementMode) String() string {
	return proto.EnumName(EnforcementMode_name, int32(x))
}

func (EnforcementMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{1}
}

// EmergencyMode is a governance-controlled circuit breaker.
type EmergencyMode int32

const (
	EmergencyMode_EMERGENCY_MODE_UNSPECIFIED            EmergencyMode = 0
	EmergencyMode_EMERGENCY_MODE_NORMAL                 EmergencyMode = 1
	EmergencyMode_EMERGENCY_MODE_PAUSE_NEW_KEYS         EmergencyMode = 2
	EmergencyMode_EMERGENCY_MODE_PAUSE_PQC_TRANSACTIONS EmergencyMode = 3
)

var EmergencyMode_name = map[int32]string{
	0: "EMERGENCY_MODE_UNSPECIFIED",
	1: "EMERGENCY_MODE_NORMAL",
	2: "EMERGENCY_MODE_PAUSE_NEW_KEYS",
	3: "EMERGENCY_MODE_PAUSE_PQC_TRANSACTIONS",
}

var EmergencyMode_value = map[string]int32{
	"EMERGENCY_MODE_UNSPECIFIED":            0,
	"EMERGENCY_MODE_NORMAL":                 1,
	"EMERGENCY_MODE_PAUSE_NEW_KEYS":         2,
	"EMERGENCY_MODE_PAUSE_PQC_TRANSACTIONS": 3,
}

func (x EmergencyMode) String() string {
	return proto.EnumName(EmergencyMode_name, int32(x))
}

func (EmergencyMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{2}
}

// KeyRole separates transaction-signing keys from recovery keys.
type KeyRole int32

const (
	KeyRole_KEY_ROLE_UNSPECIFIED KeyRole = 0
	KeyRole_KEY_ROLE_SIGNING     KeyRole = 1
	KeyRole_KEY_ROLE_RECOVERY    KeyRole = 2
)

var KeyRole_name = map[int32]string{
	0: "KEY_ROLE_UNSPECIFIED",
	1: "KEY_ROLE_SIGNING",
	2: "KEY_ROLE_RECOVERY",
}

var KeyRole_value = map[string]int32{
	"KEY_ROLE_UNSPECIFIED": 0,
	"KEY_ROLE_SIGNING":     1,
	"KEY_ROLE_RECOVERY":    2,
}

func (x KeyRole) String() string {
	return proto.EnumName(KeyRole_name, int32(x))
}

func (KeyRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{3}
}

// KeyStatus records an irreversible lifecycle state. Height windows determine
// whether a non-revoked key is currently effective.
type KeyStatus int32

const (
	KeyStatus_KEY_STATUS_UNSPECIFIED KeyStatus = 0
	KeyStatus_KEY_STATUS_LIVE        KeyStatus = 1
	KeyStatus_KEY_STATUS_REVOKED     KeyStatus = 2
)

var KeyStatus_name = map[int32]string{
	0: "KEY_STATUS_UNSPECIFIED",
	1: "KEY_STATUS_LIVE",
	2: "KEY_STATUS_REVOKED",
}

var KeyStatus_value = map[string]int32{
	"KEY_STATUS_UNSPECIFIED": 0,
	"KEY_STATUS_LIVE":        1,
	"KEY_STATUS_REVOKED":     2,
}

func (x KeyStatus) String() string {
	return proto.EnumName(KeyStatus_name, int32(x))
}

func (KeyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{4}
}

// Params are bounded consensus parameters for the pqcauth module.
type Params struct {
	EnforcementMode          EnforcementMode  `protobuf:"varint,1,opt,name=enforcement_mode,json=enforcementMode,proto3,enum=doravota.pqcauth.v1.EnforcementMode" json:"enforcement_mode,omitempty"`
	NetworkId                []byte           `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	AllowedAlgorithms        []Algorithm      `protobuf:"varint,3,rep,packed,name=allowed_algorithms,json=allowedAlgorithms,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"allowed_algorithms,omitempty"`
	SignatureVerificationGas uint64           `protobuf:"varint,4,opt,name=signature_verification_gas,json=signatureVerificationGas,proto3" json:"signature_verification_gas,omitempty"`
	ProofVerificationGas     uint64           `protobuf:"varint,5,opt,name=proof_verification_gas,json=proofVerificationGas,proto3" json:"proof_verification_gas,omitempty"`
	MaxPqcSigners            uint32           `protobuf:"varint,6,opt,name=max_pqc_signers,json=maxPqcSigners,proto3" json:"max_pqc_signers,omitempty"`
	MaxPqcAuthBytes          uint32           `protobuf:"varint,7,opt,name=max_pqc_auth_bytes,json=maxPqcAuthBytes,proto3" json:"max_pqc_auth_bytes,omitempty"`
	MaxKeysPerAccount        uint32           `protobuf:"varint,8,opt,name=max_keys_per_account,json=maxKeysPerAccount,proto3" json:"max_keys_per_account,omitempty"`
	RegistrationCutoffHeight uint64           `protobuf:"varint,9,opt,name=registration_cutoff_height,json=registrationCutoffHeight,proto3" json:"registration_cutoff_height,omitempty"`
	EmergencyMode            EmergencyMode    `protobuf:"varint,10,opt,name=emergency_mode,json=emergencyMode,proto3,enum=doravota.pqcauth.v1.EmergencyMode" json:"emergency_mode,omitempty"`
	Pending                  *ScheduledParams `protobuf:"bytes,11,opt,name=pending,proto3" json:"pending,omitempty"`
	PendingActivationHeight  uint64           `protobuf:"varint,12,opt,name=pending_activation_height,json=pendingActivationHeight,proto3" json:"pending_activation_height,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnforcementMode() EnforcementMode {
	if m != nil {
		return m.EnforcementMode
	}
	return EnforcementMode_ENFORCEMENT_MODE_UNSPECIFIED
}

func (m *Params) GetNetworkId() []byte {
	if m != nil {
		return m.NetworkId
	}
	return nil
}

func (m *Params) GetAllowedAlgorithms() []Algorithm {
	if m != nil {
		return m.AllowedAlgorithms
	}
	return nil
}

func (m *Params) GetSignatureVerificationGas() uint64 {
	if m != nil {
		return m.SignatureVerificationGas
	}
	return 0
}

func (m *Params) GetProofVerificationGas() uint64 {
	if m != nil {
		return m.ProofVerificationGas
	}
	return 0
}

func (m *Params) GetMaxPqcSigners() uint32 {
	if m != nil {
		return m.MaxPqcSigners
	}
	return 0
}

func (m *Params) GetMaxPqcAuthBytes() uint32 {
	if m != nil {
		return m.MaxPqcAuthBytes
	}
	return 0
}

func (m *Params) GetMaxKeysPerAccount() uint32 {
	if m != nil {
		return m.MaxKeysPerAccount
	}
	return 0
}

func (m *Params) GetRegistrationCutoffHeight() uint64 {
	if m != nil {
		return m.RegistrationCutoffHeight
	}
	return 0
}

func (m *Params) GetEmergencyMode() EmergencyMode {
	if m != nil {
		return m.EmergencyMode
	}
	return EmergencyMode_EMERGENCY_MODE_UNSPECIFIED
}

func (m *Params) GetPending() *ScheduledParams {
	if m != nil {
		return m.Pending
	}
	return nil
}

func (m *Params) GetPendingActivationHeight() uint64 {
	if m != nil {
		return m.PendingActivationHeight
	}
	return 0
}

// ScheduledParams contains every mutable, consensus-sensitive parameter. The
// complete bundle activates atomically at pending_activation_height.
type ScheduledParams struct {
	EnforcementMode          EnforcementMode `protobuf:"varint,1,opt,name=enforcement_mode,json=enforcementMode,proto3,enum=doravota.pqcauth.v1.EnforcementMode" json:"enforcement_mode,omitempty"`
	AllowedAlgorithms        []Algorithm     `protobuf:"varint,2,rep,packed,name=allowed_algorithms,json=allowedAlgorithms,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"allowed_algorithms,omitempty"`
	SignatureVerificationGas uint64          `protobuf:"varint,3,opt,name=signature_verification_gas,json=signatureVerificationGas,proto3" json:"signature_verification_gas,omitempty"`
	ProofVerificationGas     uint64          `protobuf:"varint,4,opt,name=proof_verification_gas,json=proofVerificationGas,proto3" json:"proof_verification_gas,omitempty"`
	MaxPqcSigners            uint32          `protobuf:"varint,5,opt,name=max_pqc_signers,json=maxPqcSigners,proto3" json:"max_pqc_signers,omitempty"`
	MaxPqcAuthBytes          uint32          `protobuf:"varint,6,opt,name=max_pqc_auth_bytes,json=maxPqcAuthBytes,proto3" json:"max_pqc_auth_bytes,omitempty"`
	MaxKeysPerAccount        uint32          `protobuf:"varint,7,opt,name=max_keys_per_account,json=maxKeysPerAccount,proto3" json:"max_keys_per_account,omitempty"`
	RegistrationCutoffHeight uint64          `protobuf:"varint,8,opt,name=registration_cutoff_height,json=registrationCutoffHeight,proto3" json:"registration_cutoff_height,omitempty"`
	EmergencyMode            EmergencyMode   `protobuf:"varint,9,opt,name=emergency_mode,json=emergencyMode,proto3,enum=doravota.pqcauth.v1.EmergencyMode" json:"emergency_mode,omitempty"`
}

func (m *ScheduledParams) Reset()         { *m = ScheduledParams{} }
func (m *ScheduledParams) String() string { return proto.CompactTextString(m) }
func (*ScheduledParams) ProtoMessage()    {}
func (*ScheduledParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{1}
}
func (m *ScheduledParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduledParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduledParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduledParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledParams.Merge(m, src)
}
func (m *ScheduledParams) XXX_Size() int {
	return m.Size()
}
func (m *ScheduledParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledParams.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledParams proto.InternalMessageInfo

func (m *ScheduledParams) GetEnforcementMode() EnforcementMode {
	if m != nil {
		return m.EnforcementMode
	}
	return EnforcementMode_ENFORCEMENT_MODE_UNSPECIFIED
}

func (m *ScheduledParams) GetAllowedAlgorithms() []Algorithm {
	if m != nil {
		return m.AllowedAlgorithms
	}
	return nil
}

func (m *ScheduledParams) GetSignatureVerificationGas() uint64 {
	if m != nil {
		return m.SignatureVerificationGas
	}
	return 0
}

func (m *ScheduledParams) GetProofVerificationGas() uint64 {
	if m != nil {
		return m.ProofVerificationGas
	}
	return 0
}

func (m *ScheduledParams) GetMaxPqcSigners() uint32 {
	if m != nil {
		return m.MaxPqcSigners
	}
	return 0
}

func (m *ScheduledParams) GetMaxPqcAuthBytes() uint32 {
	if m != nil {
		return m.MaxPqcAuthBytes
	}
	return 0
}

func (m *ScheduledParams) GetMaxKeysPerAccount() uint32 {
	if m != nil {
		return m.MaxKeysPerAccount
	}
	return 0
}

func (m *ScheduledParams) GetRegistrationCutoffHeight() uint64 {
	if m != nil {
		return m.RegistrationCutoffHeight
	}
	return 0
}

func (m *ScheduledParams) GetEmergencyMode() EmergencyMode {
	if m != nil {
		return m.EmergencyMode
	}
	return EmergencyMode_EMERGENCY_MODE_UNSPECIFIED
}

// PQCKeyRecord is an append-only key record. inactive_from_height is exclusive;
// zero means that the key has no scheduled end height.
type PQCKeyRecord struct {
	Owner              string    `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	KeyId              uint64    `protobuf:"varint,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm          Algorithm `protobuf:"varint,3,opt,name=algorithm,proto3,enum=doravota.pqcauth.v1.Algorithm" json:"algorithm,omitempty"`
	PublicKey          []byte    `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Role               KeyRole   `protobuf:"varint,5,opt,name=role,proto3,enum=doravota.pqcauth.v1.KeyRole" json:"role,omitempty"`
	Status             KeyStatus `protobuf:"varint,6,opt,name=status,proto3,enum=doravota.pqcauth.v1.KeyStatus" json:"status,omitempty"`
	CreatedHeight      uint64    `protobuf:"varint,7,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	EffectiveHeight    uint64    `protobuf:"varint,8,opt,name=effective_height,json=effectiveHeight,proto3" json:"effective_height,omitempty"`
	InactiveFromHeight uint64    `protobuf:"varint,9,opt,name=inactive_from_height,json=inactiveFromHeight,proto3" json:"inactive_from_height,omitempty"`
}

func (m *PQCKeyRecord) Reset()         { *m = PQCKeyRecord{} }
func (m *PQCKeyRecord) String() string { return proto.CompactTextString(m) }
func (*PQCKeyRecord) ProtoMessage()    {}
func (*PQCKeyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{2}
}
func (m *PQCKeyRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PQCKeyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PQCKeyRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PQCKeyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQCKeyRecord.Merge(m, src)
}
func (m *PQCKeyRecord) XXX_Size() int {
	return m.Size()
}
func (m *PQCKeyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PQCKeyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PQCKeyRecord proto.InternalMessageInfo

func (m *PQCKeyRecord) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PQCKeyRecord) GetKeyId() uint64 {
	if m != nil {
		return m.KeyId
	}
	return 0
}

func (m *PQCKeyRecord) GetAlgorithm() Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (m *PQCKeyRecord) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PQCKeyRecord) GetRole() KeyRole {
	if m != nil {
		return m.Role
	}
	return KeyRole_KEY_ROLE_UNSPECIFIED
}

func (m *PQCKeyRecord) GetStatus() KeyStatus {
	if m != nil {
		return m.Status
	}
	return KeyStatus_KEY_STATUS_UNSPECIFIED
}

func (m *PQCKeyRecord) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *PQCKeyRecord) GetEffectiveHeight() uint64 {
	if m != nil {
		return m.EffectiveHeight
	}
	return 0
}

func (m *PQCKeyRecord) GetInactiveFromHeight() uint64 {
	if m != nil {
		return m.InactiveFromHeight
	}
	return 0
}

// AccountPolicy contains the current and H+1 pending authorization state.
type AccountPolicy struct {
	Owner                  string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	CurrentSigningKeyId    uint64 `protobuf:"varint,2,opt,name=current_signing_key_id,json=currentSigningKeyId,proto3" json:"current_signing_key_id,omitempty"`
	PendingSigningKeyId    uint64 `protobuf:"varint,3,opt,name=pending_signing_key_id,json=pendingSigningKeyId,proto3" json:"pending_signing_key_id,omitempty"`
	PendingEffectiveHeight uint64 `protobuf:"varint,4,opt,name=pending_effective_height,json=pendingEffectiveHeight,proto3" json:"pending_effective_height,omitempty"`
	SelfEnforced           bool   `protobuf:"varint,5,opt,name=self_enforced,json=selfEnforced,proto3" json:"self_enforced,omitempty"`
	PendingSelfEnforced    bool   `protobuf:"varint,6,opt,name=pending_self_enforced,json=pendingSelfEnforced,proto3" json:"pending_self_enforced,omitempty"`
	PolicyVersion          uint64 `protobuf:"varint,7,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PendingPolicyVersion   uint64 `protobuf:"varint,8,opt,name=pending_policy_version,json=pendingPolicyVersion,proto3" json:"pending_policy_version,omitempty"`
	RecoveryKeyId          uint64 `protobuf:"varint,9,opt,name=recovery_key_id,json=recoveryKeyId,proto3" json:"recovery_key_id,omitempty"`
	PendingRecoveryKeyId   uint64 `protobuf:"varint,10,opt,name=pending_recovery_key_id,json=pendingRecoveryKeyId,proto3" json:"pending_recovery_key_id,omitempty"`
}

func (m *AccountPolicy) Reset()         { *m = AccountPolicy{} }
func (m *AccountPolicy) String() string { return proto.CompactTextString(m) }
func (*AccountPolicy) ProtoMessage()    {}
func (*AccountPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{3}
}
func (m *AccountPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPolicy.Merge(m, src)
}
func (m *AccountPolicy) XXX_Size() int {
	return m.Size()
}
func (m *AccountPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPolicy proto.InternalMessageInfo

func (m *AccountPolicy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AccountPolicy) GetCurrentSigningKeyId() uint64 {
	if m != nil {
		return m.CurrentSigningKeyId
	}
	return 0
}

func (m *AccountPolicy) GetPendingSigningKeyId() uint64 {
	if m != nil {
		return m.PendingSigningKeyId
	}
	return 0
}

func (m *AccountPolicy) GetPendingEffectiveHeight() uint64 {
	if m != nil {
		return m.PendingEffectiveHeight
	}
	return 0
}

func (m *AccountPolicy) GetSelfEnforced() bool {
	if m != nil {
		return m.SelfEnforced
	}
	return false
}

func (m *AccountPolicy) GetPendingSelfEnforced() bool {
	if m != nil {
		return m.PendingSelfEnforced
	}
	return false
}

func (m *AccountPolicy) GetPolicyVersion() uint64 {
	if m != nil {
		return m.PolicyVersion
	}
	return 0
}

func (m *AccountPolicy) GetPendingPolicyVersion() uint64 {
	if m != nil {
		return m.PendingPolicyVersion
	}
	return 0
}

func (m *AccountPolicy) GetRecoveryKeyId() uint64 {
	if m != nil {
		return m.RecoveryKeyId
	}
	return 0
}

func (m *AccountPolicy) GetPendingRecoveryKeyId() uint64 {
	if m != nil {
		return m.PendingRecoveryKeyId
	}
	return 0
}

// AccountKeySequence allocates monotonically increasing key identifiers.
type AccountKeySequence struct {
	Owner     string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	NextKeyId uint64 `protobuf:"varint,2,opt,name=next_key_id,json=nextKeyId,proto3" json:"next_key_id,omitempty"`
}

func (m *AccountKeySequence) Reset()         { *m = AccountKeySequence{} }
func (m *AccountKeySequence) String() string { return proto.CompactTextString(m) }
func (*AccountKeySequence) ProtoMessage()    {}
func (*AccountKeySequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{4}
}
func (m *AccountKeySequence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountKeySequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountKeySequence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountKeySequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountKeySequence.Merge(m, src)
}
func (m *AccountKeySequence) XXX_Size() int {
	return m.Size()
}
func (m *AccountKeySequence) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountKeySequence.DiscardUnknown(m)
}

var xxx_messageInfo_AccountKeySequence proto.InternalMessageInfo

func (m *AccountKeySequence) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AccountKeySequence) GetNextKeyId() uint64 {
	if m != nil {
		return m.NextKeyId
	}
	return 0
}

// GenesisState defines pqcauth genesis state.
type GenesisState struct {
	Params       Params               `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Keys         []PQCKeyRecord       `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys"`
	Policies     []AccountPolicy      `protobuf:"bytes,3,rep,name=policies,proto3" json:"policies"`
	KeySequences []AccountKeySequence `protobuf:"bytes,4,rep,name=key_sequences,json=keySequences,proto3" json:"key_sequences"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_03486e126c6af792, []int{5}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetKeys() []PQCKeyRecord {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GenesisState) GetPolicies() []AccountPolicy {
	if m != nil {
		return m.Policies
	}
	return nil
}

func (m *GenesisState) GetKeySequences() []AccountKeySequence {
	if m != nil {
		return m.KeySequences
	}
	return nil
}

func init() {
	proto.RegisterEnum("doravota.pqcauth.v1.Algorithm", Algorithm_name, Algorithm_value)
	proto.RegisterEnum("doravota.pqcauth.v1.EnforcementMode", EnforcementMode_name, EnforcementMode_value)
	proto.RegisterEnum("doravota.pqcauth.v1.EmergencyMode", EmergencyMode_name, EmergencyMode_value)
	proto.RegisterEnum("doravota.pqcauth.v1.KeyRole", KeyRole_name, KeyRole_value)
	proto.RegisterEnum("doravota.pqcauth.v1.KeyStatus", KeyStatus_name, KeyStatus_value)
	proto.RegisterType((*Params)(nil), "doravota.pqcauth.v1.Params")
	proto.RegisterType((*ScheduledParams)(nil), "doravota.pqcauth.v1.ScheduledParams")
	proto.RegisterType((*PQCKeyRecord)(nil), "doravota.pqcauth.v1.PQCKeyRecord")
	proto.RegisterType((*AccountPolicy)(nil), "doravota.pqcauth.v1.AccountPolicy")
	proto.RegisterType((*AccountKeySequence)(nil), "doravota.pqcauth.v1.AccountKeySequence")
	proto.RegisterType((*GenesisState)(nil), "doravota.pqcauth.v1.GenesisState")
}

func init() { proto.RegisterFile("doravota/pqcauth/v1/state.proto", fileDescriptor_03486e126c6af792) }

var fileDescriptor_03486e126c6af792 = []byte{
	// 1322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4d, 0x73, 0xda, 0x56,
	0x14, 0xb5, 0x0c, 0xc6, 0xe6, 0x1a, 0x8c, 0xf2, 0x8c, 0x1d, 0xec, 0x26, 0x84, 0xb8, 0x4d, 0x4a,
	0xdc, 0x8e, 0x49, 0x9c, 0x26, 0xd3, 0x8f, 0x4c, 0x3b, 0x18, 0x64, 0x42, 0xf9, 0xcc, 0x13, 0x76,
	0xc7, 0xdd, 0x68, 0x64, 0xe9, 0x01, 0x1a, 0x83, 0x1e, 0x7e, 0x12, 0x8e, 0xf9, 0x03, 0x5d, 0x77,
	0xd9, 0x65, 0x97, 0xfd, 0x01, 0x5d, 0x77, 0xd9, 0xc9, 0x32, 0xcb, 0xae, 0x32, 0x1d, 0xe7, 0x8f,
	0x74, 0xf4, 0xf4, 0x61, 0xc0, 0xb8, 0x6d, 0x32, 0xed, 0x0e, 0xdd, 0x7b, 0xee, 0xf5, 0xbb, 0xf7,
	0x9c, 0x77, 0x64, 0xc1, 0x1d, 0x9d, 0x32, 0xf5, 0x8c, 0xda, 0x6a, 0x6e, 0x70, 0xaa, 0xa9, 0x43,
	0xbb, 0x9b, 0x3b, 0x7b, 0x94, 0xb3, 0x6c, 0xd5, 0x26, 0x3b, 0x03, 0x46, 0x6d, 0x8a, 0x56, 0x7d,
	0xc0, 0x8e, 0x07, 0xd8, 0x39, 0x7b, 0xb4, 0x99, 0xec, 0xd0, 0x0e, 0xe5, 0xf9, 0x9c, 0xf3, 0xcb,
	0x85, 0x6e, 0xfd, 0xbe, 0x00, 0x91, 0xa6, 0xca, 0xd4, 0xbe, 0x85, 0x1a, 0x20, 0x12, 0xb3, 0x4d,
	0x99, 0x46, 0xfa, 0xc4, 0xb4, 0x95, 0x3e, 0xd5, 0x49, 0x4a, 0xc8, 0x08, 0xd9, 0x95, 0xdd, 0x8f,
	0x76, 0x66, 0x34, 0xdc, 0x91, 0x2e, 0xc1, 0x35, 0xaa, 0x13, 0x9c, 0x20, 0x93, 0x01, 0x74, 0x1b,
	0xc0, 0x24, 0xf6, 0x4b, 0xca, 0x4e, 0x14, 0x43, 0x4f, 0xcd, 0x67, 0x84, 0x6c, 0x0c, 0x47, 0xbd,
	0x48, 0x59, 0x47, 0x35, 0x40, 0x6a, 0xaf, 0x47, 0x5f, 0x12, 0x5d, 0x51, 0x7b, 0x1d, 0xca, 0x0c,
	0xbb, 0xdb, 0xb7, 0x52, 0xa1, 0x4c, 0x28, 0xbb, 0xb2, 0x9b, 0x9e, 0xf9, 0x17, 0xf3, 0x3e, 0x0c,
	0xdf, 0xf0, 0x2a, 0x83, 0x88, 0x85, 0x9e, 0xc1, 0xa6, 0x65, 0x74, 0x4c, 0xd5, 0x1e, 0x32, 0xa2,
	0x9c, 0x11, 0x66, 0xb4, 0x0d, 0x4d, 0xb5, 0x0d, 0x6a, 0x2a, 0x1d, 0xd5, 0x4a, 0x85, 0x33, 0x42,
	0x36, 0x8c, 0x53, 0x01, 0xe2, 0x70, 0x0c, 0x50, 0x52, 0x2d, 0xf4, 0x19, 0xac, 0x0f, 0x18, 0xa5,
	0xed, 0xab, 0x95, 0x0b, 0xbc, 0x32, 0xc9, 0xb3, 0xd3, 0x55, 0xf7, 0x21, 0xd1, 0x57, 0xcf, 0x95,
	0xc1, 0xa9, 0xa6, 0x38, 0x9d, 0x09, 0xb3, 0x52, 0x91, 0x8c, 0x90, 0x8d, 0xe3, 0x78, 0x5f, 0x3d,
	0x6f, 0x9e, 0x6a, 0xb2, 0x1b, 0x44, 0x9f, 0x00, 0xf2, 0x71, 0xce, 0x2c, 0xca, 0xf1, 0xc8, 0x26,
	0x56, 0x6a, 0x91, 0x43, 0x13, 0x2e, 0x34, 0x3f, 0xb4, 0xbb, 0x7b, 0x4e, 0x18, 0xe5, 0x20, 0xe9,
	0x80, 0x4f, 0xc8, 0xc8, 0x52, 0x06, 0x84, 0x29, 0xaa, 0xa6, 0xd1, 0xa1, 0x69, 0xa7, 0x96, 0x38,
	0xfc, 0x46, 0x5f, 0x3d, 0xaf, 0x90, 0x91, 0xd5, 0x24, 0x2c, 0xef, 0x26, 0x9c, 0xc9, 0x19, 0xe9,
	0x18, 0x96, 0xcd, 0xdc, 0x53, 0x6b, 0x43, 0x9b, 0xb6, 0xdb, 0x4a, 0x97, 0x18, 0x9d, 0xae, 0x9d,
	0x8a, 0xba, 0x93, 0x8f, 0x23, 0x0a, 0x1c, 0xf0, 0x9c, 0xe7, 0x51, 0x19, 0x56, 0x48, 0x9f, 0xb0,
	0x0e, 0x31, 0xb5, 0x91, 0x4b, 0x3a, 0x70, 0xd2, 0xb7, 0x66, 0x93, 0xee, 0x43, 0x39, 0xe5, 0x71,
	0x32, 0xfe, 0x88, 0xbe, 0x86, 0xc5, 0x01, 0x31, 0x75, 0xc3, 0xec, 0xa4, 0x96, 0x33, 0x42, 0x76,
	0xf9, 0x1a, 0xe1, 0xc8, 0x5a, 0x97, 0xe8, 0xc3, 0x1e, 0xd1, 0x5d, 0xe1, 0x61, 0xbf, 0x08, 0x7d,
	0x09, 0x1b, 0xde, 0x4f, 0x45, 0xd5, 0x6c, 0xe3, 0xcc, 0x1d, 0xc7, 0x9b, 0x23, 0xc6, 0xe7, 0xb8,
	0xe9, 0x01, 0xf2, 0x41, 0xde, 0x1d, 0x63, 0xeb, 0xd7, 0x30, 0x24, 0xa6, 0x1a, 0xff, 0xf7, 0x8a,
	0x9e, 0x2d, 0xd9, 0xf9, 0xff, 0x47, 0xb2, 0xa1, 0xf7, 0x96, 0x6c, 0xf8, 0xdd, 0x24, 0xbb, 0xf0,
	0xef, 0x25, 0x1b, 0x79, 0x37, 0xc9, 0x2e, 0xbe, 0x9f, 0x64, 0x97, 0xde, 0x59, 0xb2, 0xd1, 0xf7,
	0x94, 0xec, 0xd6, 0x0f, 0x21, 0x88, 0x35, 0x5f, 0x14, 0x2a, 0x64, 0x84, 0x89, 0x46, 0x99, 0x8e,
	0x92, 0xb0, 0x40, 0x5f, 0x9a, 0x84, 0x71, 0xa1, 0x44, 0xb1, 0xfb, 0x80, 0xd6, 0x20, 0x72, 0x42,
	0x46, 0xbe, 0x8d, 0x85, 0xf1, 0xc2, 0x09, 0x19, 0x95, 0x75, 0xf4, 0x0c, 0xa2, 0x81, 0x0e, 0x38,
	0x5f, 0xff, 0x2c, 0x83, 0xcb, 0x02, 0xc7, 0x1f, 0x07, 0xc3, 0xe3, 0x9e, 0xa1, 0x39, 0x8b, 0xe3,
	0xa4, 0xc5, 0x70, 0xd4, 0x8d, 0x54, 0xc8, 0x08, 0x3d, 0x84, 0x30, 0xa3, 0x3d, 0xc2, 0xe9, 0x59,
	0xd9, 0xbd, 0x35, 0xb3, 0xaf, 0x73, 0x6e, 0xda, 0x23, 0x98, 0x23, 0xd1, 0x53, 0x88, 0x38, 0xaf,
	0x81, 0xa1, 0xcb, 0xd3, 0x75, 0x67, 0xa9, 0x90, 0x91, 0xcc, 0x51, 0xd8, 0x43, 0xa3, 0x7b, 0xb0,
	0xa2, 0x31, 0xa2, 0xda, 0x44, 0xf7, 0x19, 0x58, 0xe4, 0x53, 0xc6, 0xbd, 0xa8, 0xb7, 0xf6, 0x07,
	0x20, 0x92, 0x76, 0x9b, 0x38, 0x37, 0x8f, 0x4c, 0x52, 0x95, 0x08, 0xe2, 0x1e, 0xf4, 0x21, 0x24,
	0x0d, 0x53, 0x75, 0x91, 0x6d, 0x46, 0xfb, 0x93, 0x66, 0x84, 0xfc, 0xdc, 0x3e, 0xa3, 0x7d, 0xef,
	0xfe, 0xbe, 0x09, 0x41, 0xdc, 0x53, 0x47, 0x93, 0xf6, 0x0c, 0x6d, 0x74, 0x0d, 0x13, 0x8f, 0x61,
	0x5d, 0x1b, 0x32, 0xe6, 0xdc, 0x67, 0x47, 0xbf, 0x8e, 0x57, 0x4c, 0x30, 0xb3, 0xea, 0x65, 0x65,
	0x37, 0x59, 0xe1, 0x3c, 0x3d, 0x86, 0x75, 0xdf, 0x58, 0xa6, 0x8a, 0xdc, 0x4b, 0xb6, 0xea, 0x65,
	0x27, 0x8a, 0x3e, 0x87, 0x94, 0x5f, 0x74, 0x65, 0x6c, 0xf7, 0x86, 0xf9, 0x4d, 0xa5, 0xa9, 0xe9,
	0x3f, 0x84, 0xb8, 0x45, 0x7a, 0x6d, 0xc5, 0xb3, 0x0f, 0x9d, 0x53, 0xb8, 0x84, 0x63, 0x4e, 0xd0,
	0xf3, 0x18, 0x1d, 0xed, 0xc2, 0x5a, 0x70, 0xa6, 0x09, 0x70, 0x84, 0x83, 0x83, 0x23, 0x8d, 0xd7,
	0xdc, 0x83, 0x95, 0x01, 0x5f, 0x8e, 0x73, 0xe7, 0x2d, 0x83, 0x9a, 0x3e, 0x51, 0x6e, 0xf4, 0xd0,
	0x0d, 0x72, 0x67, 0xf0, 0x5a, 0x4f, 0xc1, 0x97, 0x3c, 0x67, 0x70, 0xb3, 0xcd, 0x89, 0xaa, 0xfb,
	0x90, 0x60, 0x44, 0xa3, 0x67, 0x84, 0x8d, 0xfc, 0xed, 0xb8, 0x74, 0xc5, 0xfd, 0xb0, 0xbb, 0x97,
	0x27, 0xe0, 0x9b, 0xb0, 0x32, 0x8d, 0x87, 0x89, 0xf6, 0x78, 0xbc, 0x6c, 0xeb, 0x5b, 0x40, 0x1e,
	0xbf, 0x8e, 0x00, 0xc9, 0xe9, 0x90, 0x98, 0x1a, 0xb9, 0x86, 0xe4, 0x34, 0x2c, 0x9b, 0xe4, 0xdc,
	0x9e, 0x64, 0x36, 0xea, 0x84, 0xdc, 0x5e, 0x3f, 0xcf, 0x43, 0xac, 0x44, 0x4c, 0x62, 0x19, 0x96,
	0x23, 0x65, 0x82, 0xbe, 0x80, 0xc8, 0x80, 0x7b, 0x3e, 0xef, 0xb3, 0xbc, 0xfb, 0xc1, 0x4c, 0xe5,
	0xbb, 0xaf, 0x85, 0xbd, 0xf0, 0xab, 0x37, 0x77, 0xe6, 0xb0, 0x57, 0x80, 0xbe, 0x82, 0xb0, 0xe3,
	0x5b, 0xdc, 0xc5, 0x97, 0x77, 0xef, 0xce, 0x2e, 0x1c, 0x73, 0x08, 0xaf, 0x9c, 0x17, 0xa1, 0x22,
	0x2c, 0xf1, 0x0d, 0x1b, 0xc4, 0xfd, 0xcf, 0x65, 0xf9, 0x1a, 0x0f, 0x9a, 0x50, 0xb6, 0xd7, 0x21,
	0xa8, 0x44, 0x18, 0xe2, 0xce, 0xa4, 0x96, 0xb7, 0x14, 0xc7, 0xc0, 0x9d, 0x56, 0x1f, 0xff, 0x5d,
	0xab, 0xb1, 0x25, 0x7a, 0xfd, 0x62, 0x27, 0x97, 0x21, 0x6b, 0xfb, 0x1b, 0x88, 0x06, 0xa6, 0x83,
	0x36, 0x60, 0x2d, 0x5f, 0x2d, 0x35, 0x70, 0xb9, 0xf5, 0xbc, 0xa6, 0x1c, 0xd4, 0xe5, 0xa6, 0x54,
	0x28, 0xef, 0x97, 0xa5, 0xa2, 0x38, 0x87, 0x6e, 0xc2, 0xea, 0x65, 0xaa, 0x56, 0x55, 0x8a, 0x72,
	0x5e, 0x79, 0xfa, 0x44, 0x14, 0xb6, 0x7f, 0x13, 0x20, 0x31, 0xf5, 0x42, 0x44, 0x19, 0xb8, 0x25,
	0xd5, 0xf7, 0x1b, 0xb8, 0x20, 0xd5, 0xa4, 0x7a, 0x4b, 0xa9, 0x35, 0x8a, 0xd2, 0x54, 0xbb, 0xdb,
	0xb0, 0x71, 0x05, 0x51, 0x2c, 0xcb, 0xf9, 0xbd, 0xaa, 0x54, 0x14, 0x85, 0x99, 0xe9, 0x46, 0xb3,
	0x55, 0x6e, 0xd4, 0xf3, 0x55, 0x71, 0x1e, 0x7d, 0x0a, 0xd9, 0x2b, 0x69, 0x2c, 0xbd, 0x38, 0x28,
	0x63, 0xa9, 0xa8, 0xec, 0x37, 0xb0, 0x82, 0xa5, 0x52, 0x59, 0x6e, 0x49, 0x58, 0x2a, 0x8a, 0xa1,
	0x99, 0xcd, 0x7c, 0xb4, 0x18, 0xde, 0xfe, 0x49, 0x80, 0xf8, 0x84, 0xf7, 0xa3, 0x34, 0x6c, 0x4a,
	0x35, 0x09, 0x97, 0xa4, 0x7a, 0xe1, 0x68, 0xd6, 0xe1, 0x37, 0x60, 0x6d, 0x2a, 0x5f, 0x6f, 0xe0,
	0x5a, 0xbe, 0x2a, 0x0a, 0xe8, 0x2e, 0xdc, 0x9e, 0x4a, 0x35, 0xf3, 0x07, 0xb2, 0xa4, 0xd4, 0xa5,
	0xef, 0x94, 0x8a, 0x74, 0x24, 0x8b, 0xf3, 0xe8, 0x01, 0xdc, 0x9b, 0x09, 0x69, 0xbe, 0x28, 0x28,
	0x2d, 0x9c, 0xaf, 0xcb, 0xf9, 0x82, 0x33, 0xa8, 0x2c, 0x86, 0xb6, 0x9b, 0xb0, 0xe8, 0x39, 0x37,
	0x4a, 0x41, 0xb2, 0x22, 0x1d, 0x29, 0xb8, 0x51, 0x9d, 0x3e, 0x4d, 0x12, 0xc4, 0x20, 0x23, 0x97,
	0x4b, 0xf5, 0x72, 0xbd, 0x24, 0x0a, 0x68, 0x0d, 0x6e, 0x04, 0x51, 0x2c, 0x15, 0x1a, 0x87, 0x12,
	0x3e, 0x12, 0xe7, 0xb7, 0x5b, 0x10, 0x0d, 0x7c, 0x1d, 0x6d, 0xc2, 0xba, 0x83, 0x91, 0x5b, 0xf9,
	0xd6, 0x81, 0x3c, 0xd5, 0x75, 0x15, 0x12, 0x63, 0xb9, 0x6a, 0xf9, 0x50, 0x12, 0x05, 0xb4, 0x0e,
	0x68, 0x2c, 0x88, 0xa5, 0xc3, 0x46, 0x45, 0x2a, 0x8a, 0xf3, 0x7b, 0xb5, 0x5f, 0x2e, 0xd2, 0xc2,
	0xab, 0x8b, 0xb4, 0xf0, 0xfa, 0x22, 0x2d, 0xfc, 0x79, 0x91, 0x16, 0x7e, 0x7c, 0x9b, 0x9e, 0x7b,
	0xfd, 0x36, 0x3d, 0xf7, 0xc7, 0xdb, 0xf4, 0xdc, 0xf7, 0xb9, 0x8e, 0x61, 0x77, 0x87, 0xc7, 0x3b,
	0x1a, 0xed, 0xe7, 0x8a, 0x94, 0xa9, 0xfb, 0xaa, 0x66, 0x53, 0x36, 0xca, 0x05, 0x9f, 0x27, 0xe7,
	0xc1, 0x07, 0x8a, 0x3d, 0x1a, 0x10, 0xeb, 0x38, 0xc2, 0xbf, 0x39, 0x1e, 0xff, 0x15, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x27, 0xe1, 0x37, 0xc1, 0x0c, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EnforcementMode != that1.EnforcementMode {
		return false
	}
	if !bytes.Equal(this.NetworkId, that1.NetworkId) {
		return false
	}
	if len(this.AllowedAlgorithms) != len(that1.AllowedAlgorithms) {
		return false
	}
	for i := range this.AllowedAlgorithms {
		if this.AllowedAlgorithms[i] != that1.AllowedAlgorithms[i] {
			return false
		}
	}
	if this.SignatureVerificationGas != that1.SignatureVerificationGas {
		return false
	}
	if this.ProofVerificationGas != that1.ProofVerificationGas {
		return false
	}
	if this.MaxPqcSigners != that1.MaxPqcSigners {
		return false
	}
	if this.MaxPqcAuthBytes != that1.MaxPqcAuthBytes {
		return false
	}
	if this.MaxKeysPerAccount != that1.MaxKeysPerAccount {
		return false
	}
	if this.RegistrationCutoffHeight != that1.RegistrationCutoffHeight {
		return false
	}
	if this.EmergencyMode != that1.EmergencyMode {
		return false
	}
	if !this.Pending.Equal(that1.Pending) {
		return false
	}
	if this.PendingActivationHeight != that1.PendingActivationHeight {
		return false
	}
	return true
}
func (this *ScheduledParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ScheduledParams)
	if !ok {
		that2, ok := that.(ScheduledParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EnforcementMode != that1.EnforcementMode {
		return false
	}
	if len(this.AllowedAlgorithms) != len(that1.AllowedAlgorithms) {
		return false
	}
	for i := range this.AllowedAlgorithms {
		if this.AllowedAlgorithms[i] != that1.AllowedAlgorithms[i] {
			return false
		}
	}
	if this.SignatureVerificationGas != that1.SignatureVerificationGas {
		return false
	}
	if this.ProofVerificationGas != that1.ProofVerificationGas {
		return false
	}
	if this.MaxPqcSigners != that1.MaxPqcSigners {
		return false
	}
	if this.MaxPqcAuthBytes != that1.MaxPqcAuthBytes {
		return false
	}
	if this.MaxKeysPerAccount != that1.MaxKeysPerAccount {
		return false
	}
	if this.RegistrationCutoffHeight != that1.RegistrationCutoffHeight {
		return false
	}
	if this.EmergencyMode != that1.EmergencyMode {
		return false
	}
	return true
}
func (this *PQCKeyRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PQCKeyRecord)
	if !ok {
		that2, ok := that.(PQCKeyRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.KeyId != that1.KeyId {
		return false
	}
	if this.Algorithm != that1.Algorithm {
		return false
	}
	if !bytes.Equal(this.PublicKey, that1.PublicKey) {
		return false
	}
	if this.Role != that1.Role {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.CreatedHeight != that1.CreatedHeight {
		return false
	}
	if this.EffectiveHeight != that1.EffectiveHeight {
		return false
	}
	if this.InactiveFromHeight != that1.InactiveFromHeight {
		return false
	}
	return true
}
func (this *AccountPolicy) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AccountPolicy)
	if !ok {
		that2, ok := that.(AccountPolicy)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.CurrentSigningKeyId != that1.CurrentSigningKeyId {
		return false
	}
	if this.PendingSigningKeyId != that1.PendingSigningKeyId {
		return false
	}
	if this.PendingEffectiveHeight != that1.PendingEffectiveHeight {
		return false
	}
	if this.SelfEnforced != that1.SelfEnforced {
		return false
	}
	if this.PendingSelfEnforced != that1.PendingSelfEnforced {
		return false
	}
	if this.PolicyVersion != that1.PolicyVersion {
		return false
	}
	if this.PendingPolicyVersion != that1.PendingPolicyVersion {
		return false
	}
	if this.RecoveryKeyId != that1.RecoveryKeyId {
		return false
	}
	if this.PendingRecoveryKeyId != that1.PendingRecoveryKeyId {
		return false
	}
	return true
}
func (this *AccountKeySequence) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AccountKeySequence)
	if !ok {
		that2, ok := that.(AccountKeySequence)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.NextKeyId != that1.NextKeyId {
		return false
	}
	return true
}
func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Params.Equal(&that1.Params) {
		return false
	}
	if len(this.Keys) != len(that1.Keys) {
		return false
	}
	for i := range this.Keys {
		if !this.Keys[i].Equal(&that1.Keys[i]) {
			return false
		}
	}
	if len(this.Policies) != len(that1.Policies) {
		return false
	}
	for i := range this.Policies {
		if !this.Policies[i].Equal(&that1.Policies[i]) {
			return false
		}
	}
	if len(this.KeySequences) != len(that1.KeySequences) {
		return false
	}
	for i := range this.KeySequences {
		if !this.KeySequences[i].Equal(&that1.KeySequences[i]) {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PendingActivationHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PendingActivationHeight))
		i--
		dAtA[i] = 0x60
	}
	if m.Pending != nil {
		{
			size, err := m.Pending.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintState(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.EmergencyMode != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.EmergencyMode))
		i--
		dAtA[i] = 0x50
	}
	if m.RegistrationCutoffHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RegistrationCutoffHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxKeysPerAccount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MaxKeysPerAccount))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxPqcAuthBytes != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MaxPqcAuthBytes))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxPqcSigners != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MaxPqcSigners))
		i--
		dAtA[i] = 0x30
	}
	if m.ProofVerificationGas != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ProofVerificationGas))
		i--
		dAtA[i] = 0x28
	}
	if m.SignatureVerificationGas != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.SignatureVerificationGas))
		i--
		dAtA[i] = 0x20
	}
	if len(m.AllowedAlgorithms) > 0 {
		dAtA3 := make([]byte, len(m.AllowedAlgorithms)*10)
		var j2 int
		for _, num := range m.AllowedAlgorithms {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintState(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NetworkId) > 0 {
		i -= len(m.NetworkId)
		copy(dAtA[i:], m.NetworkId)
		i = encodeVarintState(dAtA, i, uint64(len(m.NetworkId)))
		i--
		dAtA[i] = 0x12
	}
	if m.EnforcementMode != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.EnforcementMode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduledParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduledParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduledParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EmergencyMode != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.EmergencyMode))
		i--
		dAtA[i] = 0x48
	}
	if m.RegistrationCutoffHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RegistrationCutoffHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxKeysPerAccount != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MaxKeysPerAccount))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxPqcAuthBytes != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MaxPqcAuthBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxPqcSigners != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.MaxPqcSigners))
		i--
		dAtA[i] = 0x28
	}
	if m.ProofVerificationGas != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.ProofVerificationGas))
		i--
		dAtA[i] = 0x20
	}
	if m.SignatureVerificationGas != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.SignatureVerificationGas))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AllowedAlgorithms) > 0 {
		dAtA5 := make([]byte, len(m.AllowedAlgorithms)*10)
		var j4 int
		for _, num := range m.AllowedAlgorithms {
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		i -= j4
		copy(dAtA[i:], dAtA5[:j4])
		i = encodeVarintState(dAtA, i, uint64(j4))
		i--
		dAtA[i] = 0x12
	}
	if m.EnforcementMode != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.EnforcementMode))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PQCKeyRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PQCKeyRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PQCKeyRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InactiveFromHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.InactiveFromHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.EffectiveHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.EffectiveHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.Role != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintState(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.Algorithm != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Algorithm))
		i--
		dAtA[i] = 0x18
	}
	if m.KeyId != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.KeyId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintState(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PendingRecoveryKeyId != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PendingRecoveryKeyId))
		i--
		dAtA[i] = 0x50
	}
	if m.RecoveryKeyId != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.RecoveryKeyId))
		i--
		dAtA[i] = 0x48
	}
	if m.PendingPolicyVersion != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PendingPolicyVersion))
		i--
		dAtA[i] = 0x40
	}
	if m.PolicyVersion != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PolicyVersion))
		i--
		dAtA[i] = 0x38
	}
	if m.PendingSelfEnforced {
		i--
		if m.PendingSelfEnforced {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.SelfEnforced {
		i--
		if m.SelfEnforced {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.PendingEffectiveHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PendingEffectiveHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.PendingSigningKeyId != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PendingSigningKeyId))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentSigningKeyId != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.CurrentSigningKeyId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintState(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountKeySequence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountKeySequence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountKeySequence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextKeyId != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.NextKeyId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintState(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.KeySequences) > 0 {
		for iNdEx := len(m.KeySequences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeySequences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Policies) > 0 {
		for iNdEx := len(m.Policies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Policies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Keys) > 0 {
		for iNdEx := len(m.Keys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Keys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EnforcementMode != 0 {
		n += 1 + sovState(uint64(m.EnforcementMode))
	}
	l = len(m.NetworkId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if len(m.AllowedAlgorithms) > 0 {
		l = 0
		for _, e := range m.AllowedAlgorithms {
			l += sovState(uint64(e))
		}
		n += 1 + sovState(uint64(l)) + l
	}
	if m.SignatureVerificationGas != 0 {
		n += 1 + sovState(uint64(m.SignatureVerificationGas))
	}
	if m.ProofVerificationGas != 0 {
		n += 1 + sovState(uint64(m.ProofVerificationGas))
	}
	if m.MaxPqcSigners != 0 {
		n += 1 + sovState(uint64(m.MaxPqcSigners))
	}
	if m.MaxPqcAuthBytes != 0 {
		n += 1 + sovState(uint64(m.MaxPqcAuthBytes))
	}
	if m.MaxKeysPerAccount != 0 {
		n += 1 + sovState(uint64(m.MaxKeysPerAccount))
	}
	if m.RegistrationCutoffHeight != 0 {
		n += 1 + sovState(uint64(m.RegistrationCutoffHeight))
	}
	if m.EmergencyMode != 0 {
		n += 1 + sovState(uint64(m.EmergencyMode))
	}
	if m.Pending != nil {
		l = m.Pending.Size()
		n += 1 + l + sovState(uint64(l))
	}
	if m.PendingActivationHeight != 0 {
		n += 1 + sovState(uint64(m.PendingActivationHeight))
	}
	return n
}

func (m *ScheduledParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EnforcementMode != 0 {
		n += 1 + sovState(uint64(m.EnforcementMode))
	}
	if len(m.AllowedAlgorithms) > 0 {
		l = 0
		for _, e := range m.AllowedAlgorithms {
			l += sovState(uint64(e))
		}
		n += 1 + sovState(uint64(l)) + l
	}
	if m.SignatureVerificationGas != 0 {
		n += 1 + sovState(uint64(m.SignatureVerificationGas))
	}
	if m.ProofVerificationGas != 0 {
		n += 1 + sovState(uint64(m.ProofVerificationGas))
	}
	if m.MaxPqcSigners != 0 {
		n += 1 + sovState(uint64(m.MaxPqcSigners))
	}
	if m.MaxPqcAuthBytes != 0 {
		n += 1 + sovState(uint64(m.MaxPqcAuthBytes))
	}
	if m.MaxKeysPerAccount != 0 {
		n += 1 + sovState(uint64(m.MaxKeysPerAccount))
	}
	if m.RegistrationCutoffHeight != 0 {
		n += 1 + sovState(uint64(m.RegistrationCutoffHeight))
	}
	if m.EmergencyMode != 0 {
		n += 1 + sovState(uint64(m.EmergencyMode))
	}
	return n
}

func (m *PQCKeyRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.KeyId != 0 {
		n += 1 + sovState(uint64(m.KeyId))
	}
	if m.Algorithm != 0 {
		n += 1 + sovState(uint64(m.Algorithm))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovState(uint64(m.Role))
	}
	if m.Status != 0 {
		n += 1 + sovState(uint64(m.Status))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovState(uint64(m.CreatedHeight))
	}
	if m.EffectiveHeight != 0 {
		n += 1 + sovState(uint64(m.EffectiveHeight))
	}
	if m.InactiveFromHeight != 0 {
		n += 1 + sovState(uint64(m.InactiveFromHeight))
	}
	return n
}

func (m *AccountPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.CurrentSigningKeyId != 0 {
		n += 1 + sovState(uint64(m.CurrentSigningKeyId))
	}
	if m.PendingSigningKeyId != 0 {
		n += 1 + sovState(uint64(m.PendingSigningKeyId))
	}
	if m.PendingEffectiveHeight != 0 {
		n += 1 + sovState(uint64(m.PendingEffectiveHeight))
	}
	if m.SelfEnforced {
		n += 2
	}
	if m.PendingSelfEnforced {
		n += 2
	}
	if m.PolicyVersion != 0 {
		n += 1 + sovState(uint64(m.PolicyVersion))
	}
	if m.PendingPolicyVersion != 0 {
		n += 1 + sovState(uint64(m.PendingPolicyVersion))
	}
	if m.RecoveryKeyId != 0 {
		n += 1 + sovState(uint64(m.RecoveryKeyId))
	}
	if m.PendingRecoveryKeyId != 0 {
		n += 1 + sovState(uint64(m.PendingRecoveryKeyId))
	}
	return n
}

func (m *AccountKeySequence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.NextKeyId != 0 {
		n += 1 + sovState(uint64(m.NextKeyId))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovState(uint64(l))
	if len(m.Keys) > 0 {
		for _, e := range m.Keys {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.Policies) > 0 {
		for _, e := range m.Policies {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.KeySequences) > 0 {
		for _, e := range m.KeySequences {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnforcementMode", wireType)
			}
			m.EnforcementMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnforcementMode |= EnforcementMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkId = append(m.NetworkId[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkId == nil {
				m.NetworkId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v Algorithm
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Algorithm(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AllowedAlgorithms = append(m.AllowedAlgorithms, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthState
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthState
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.AllowedAlgorithms) == 0 {
					m.AllowedAlgorithms = make([]Algorithm, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Algorithm
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Algorithm(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AllowedAlgorithms = append(m.AllowedAlgorithms, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAlgorithms", wireType)
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureVerificationGas", wireType)
			}
			m.SignatureVerificationGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignatureVerificationGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofVerificationGas", wireType)
			}
			m.ProofVerificationGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofVerificationGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPqcSigners", wireType)
			}
			m.MaxPqcSigners = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPqcSigners |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPqcAuthBytes", wireType)
			}
			m.MaxPqcAuthBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPqcAuthBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxKeysPerAccount", wireType)
			}
			m.MaxKeysPerAccount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxKeysPerAccount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationCutoffHeight", wireType)
			}
			m.RegistrationCutoffHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationCutoffHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyMode", wireType)
			}
			m.EmergencyMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmergencyMode |= EmergencyMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pending", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pending == nil {
				m.Pending = &ScheduledParams{}
			}
			if err := m.Pending.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingActivationHeight", wireType)
			}
			m.PendingActivationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingActivationHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduledParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduledParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduledParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnforcementMode", wireType)
			}
			m.EnforcementMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnforcementMode |= EnforcementMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v Algorithm
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Algorithm(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AllowedAlgorithms = append(m.AllowedAlgorithms, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthState
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthState
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.AllowedAlgorithms) == 0 {
					m.AllowedAlgorithms = make([]Algorithm, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Algorithm
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Algorithm(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AllowedAlgorithms = append(m.AllowedAlgorithms, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAlgorithms", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignatureVerificationGas", wireType)
			}
			m.SignatureVerificationGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignatureVerificationGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofVerificationGas", wireType)
			}
			m.ProofVerificationGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProofVerificationGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPqcSigners", wireType)
			}
			m.MaxPqcSigners = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPqcSigners |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPqcAuthBytes", wireType)
			}
			m.MaxPqcAuthBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPqcAuthBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxKeysPerAccount", wireType)
			}
			m.MaxKeysPerAccount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxKeysPerAccount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationCutoffHeight", wireType)
			}
			m.RegistrationCutoffHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationCutoffHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyMode", wireType)
			}
			m.EmergencyMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmergencyMode |= EmergencyMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PQCKeyRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PQCKeyRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PQCKeyRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyId", wireType)
			}
			m.KeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Algorithm", wireType)
			}
			m.Algorithm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Algorithm |= Algorithm(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= KeyRole(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= KeyStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveHeight", wireType)
			}
			m.EffectiveHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InactiveFromHeight", wireType)
			}
			m.InactiveFromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InactiveFromHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentSigningKeyId", wireType)
			}
			m.CurrentSigningKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentSigningKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingSigningKeyId", wireType)
			}
			m.PendingSigningKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingSigningKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingEffectiveHeight", wireType)
			}
			m.PendingEffectiveHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingEffectiveHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelfEnforced", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SelfEnforced = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingSelfEnforced", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PendingSelfEnforced = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			m.PolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingPolicyVersion", wireType)
			}
			m.PendingPolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingPolicyVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryKeyId", wireType)
			}
			m.RecoveryKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoveryKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingRecoveryKeyId", wireType)
			}
			m.PendingRecoveryKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingRecoveryKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountKeySequence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountKeySequence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountKeySequence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextKeyId", wireType)
			}
			m.NextKeyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextKeyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keys = append(m.Keys, PQCKeyRecord{})
			if err := m.Keys[len(m.Keys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Policies = append(m.Policies, AccountPolicy{})
			if err := m.Policies[len(m.Policies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeySequences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeySequences = append(m.KeySequences, AccountKeySequence{})
			if err := m.KeySequences[len(m.KeySequences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
